"""Verify the behavior system's DOCUMENTATION cannot drift from the system.

    .venv/Scripts/python.exe tools/check_behavior_docs.py
    .venv/Scripts/python.exe tools/check_behavior_docs.py --write   # regenerate

`tools/check_behavior.py` proves the machinery works. This file proves the
paper agrees with the machinery, which is a separate failure and a worse one:
a broken behavior raises on the first frame, while a document that describes a
behavior the engine cannot run sends an AI to write a `.tmx` that raises at
load, and a document that omits one the engine CAN run means the behavior is
never used at all.

WHAT IS ASSERTED
----------------
     1. `docs/BEHAVIORS.md` is exactly what the generator produces, and its
        first half is byte-for-byte `registry.describe_all()`
     2. the catalogue in the FILE names exactly the registered behaviors,
        in both of the two places it names them
     3. every parameter the file documents is one its behavior declares
     4. every actors column a behavior consumes is declared by the genre
        pack that behavior claims  <- the one with teeth
     5. a pack's `object_types` are all spawnable, so an authored object
        cannot make the map raise at load
     6. every `pyoneer_*` property name printed in the docs or in either
        RULES.md is a real vocabulary constant, correctly spelled
     7. both RULES.md files point at the generated document, do not claim a
        behavior exists while the registry is empty, and name no `Game*`
        class that is absent from the tree
     8. the integration status written in the file matches what the code
        actually does when driven
     9. EVERY column of that integration table goes `no` when the code it
        describes is broken  <- the negative corpus

THE ONE TABLE `CLAUDE.md` TELLS EVERY READER TO TRUST
-----------------------------------------------------
`CLAUDE.md` routes readers here with the instruction to trust this document's
MEASURED integration table over any prose, including its own preamble. That
makes a detector reporting a wire which is not there the most expensive kind
of wrong available in this tree -- and the sibling instrument one file over,
`tools/check_event_docs.py`, was caught printing `yes` over broken code in
three consecutive passes.

Two of the detectors behind this table had the same two shapes. `_calls`
matched a bare `func.id`/`func.attr` with no resolution through the import
that brought the name in, so any function with a matching NAME satisfied it;
`_assigns_collision_field` was a regex over source text, which counted a
comment, a docstring and an `==`. Neither had ever been watched saying `no`.
Section 9 is the repair the sibling already carries: `ROW_KEYS` + `CORPUS`, a
gate that every row is claimed by exactly one key, and a per-row gate that it
is driven BOTH ways. Nothing in it edits a tracked file.

THE DOCUMENT IS GENERATED, INCLUDING THE PARTS THAT ARE NOT `describe_all`
-------------------------------------------------------------------------
`describe_all()` renders the registry. `render_doc()` below renders the
registry AND the two things the registry cannot see: what the surrounding
engine has actually wired up, and what each genre pack declares. Both halves
are derived -- the integration table is produced by DRIVING a real
`GameEntity`, not by reading a flag someone remembered to set -- so the whole
file is regenerated by one command and the check is an equality.

THE FIXTURES ARE THIS FILE'S OWN
--------------------------------
A rule run only over the live tree passes whenever the live tree happens to be
clean, and passes vacuously whenever it iterates nothing. So each rule below
is driven twice: once against a hand-built fixture registry and fixture genre
pack that is KNOWN to violate it, and once against the live registry and the
real packs, which must be clean. `data/maps/starter.tmx` is never read.
"""
from __future__ import annotations

import _bootstrap  # noqa: F401  (must precede engine imports)

import argparse
import ast
import json
import os
import re
import sys
import tempfile

import pygame

pygame.init()

from editor.core import genre as genre_module
from editor.core.genre import (GenreField, GenreLayer, GenreObjectClass,
                               GenrePack, GenreTable)
from scripts.core import collision_runtime, layer_profile
from scripts.core.event_manager import PyoneerEvent
from scripts.core.input import InputActionManager
from scripts.core.event_types import GameEventType
from scripts.core.spawn import SPAWN_REGISTRY
from scripts.game import behavior as behavior_package
from scripts.game.behavior import (ACTOR, BEHAVIOR_REGISTRY, BEHAVIORS,
                                   PARAM_PREFIX, TOKEN, BehaviorParam,
                                   BehaviorRequest, BehaviorSpec,
                                   EntityBehavior, EntityBehaviors,
                                   describe_all, format_list, parse_list,
                                   read_requests, validate_list)
from scripts.game.entity.game_entity import GameEntity
from scripts.loaders import map_loader

ROOT = _bootstrap.REPO_ROOT
DOC_PATH = os.path.join(ROOT, "docs", "BEHAVIORS.md")
INPUTS_PATH = os.path.join(ROOT, "config", "inputs.json")
GENRES_DIR = genre_module.GENRES_DIR

REGENERATE = ".venv/Scripts/python.exe tools/check_behavior_docs.py --write"

SENTINEL = ("<!-- Everything above this line is `describe_all()` in "
            "scripts/game/behavior/registry.py. Everything below is derived "
            "from the engine and the genre packs by tools/check_behavior_docs.py. "
            "Regenerate the whole file with:  %s  -->" % REGENERATE)

WIRED = "**Integration status: the per-frame drive is WIRED.**"
UNWIRED = "**Integration status: the per-frame drive is NOT WIRED.**"
EMPTY_MARKER = "**No behavior is registered yet.**"

failures: list[str] = []
asserted: list[str] = []


def expect(label, got, want):
    asserted.append(label)
    ok = got == want
    print(f"  {'ok  ' if ok else 'FAIL'} {label:<62} got={got!r} want={want!r}")
    if not ok:
        failures.append(label)


def expect_true(label, got):
    asserted.append(label)
    ok = bool(got)
    print(f"  {'ok  ' if ok else 'FAIL'} {label:<62} got={got!r}")
    if not ok:
        failures.append(label)


def expect_reports(label, violations, *fragments):
    """Exactly one violation, and it must name every fragment.

    The fragments are the teeth. `len(violations) == 1` passes for a
    violation raised by the wrong rule about the wrong thing, and this check
    exists precisely to distinguish "the column is missing" from "the pack is
    missing" -- two rules that share a code path and would otherwise cover
    for each other.
    """
    asserted.append(label)
    if len(violations) != 1:
        print(f"  FAIL {label:<62} {len(violations)} violation(s): {violations}")
        failures.append(label)
        return
    text = violations[0]
    missing = [f for f in fragments if f not in text]
    ok = not missing
    print(f"  {'ok  ' if ok else 'FAIL'} {label:<62} {text[:70]}")
    if not ok:
        failures.append(f"{label} (message lacks {missing})")


# ===========================================================================
# The rules. Every one is a pure function over (registry, packs, text) so it
# can be driven by a fixture that violates it and by the live tree, which
# must not.
# ===========================================================================

HEADING = re.compile(r"^### `([a-z][a-z0-9_]*)`$", re.M)
# The two tables both begin `| \`token\` | `, and telling them apart is the
# second cell: the summary table's is the integer run order, a parameter
# table's is a declared type. Matching on the token alone credited every
# parameter key as a behavior and made the catalogue assertion pass for a
# document that listed none of the right things.
SUMMARY_ROW = re.compile(r"^\| `([a-z][a-z0-9_]*)` \| \d+ \| ", re.M)
# Non-capturing on the type: `findall` returns a tuple per match the moment a
# pattern has two groups, and a list of tuples compared against a list of
# strings is never equal -- an assertion that fails for the wrong reason is
# only marginally better than one that cannot fail.
PARAM_ROW = re.compile(r"^\| `([a-z][a-z0-9_]*)` \| (?:int|float|str|bool) \| ",
                       re.M)
PYONEER_NAME = re.compile(r"\bpyoneer_[a-zA-Z0-9_]*")
GAME_CLASS = re.compile(r"\bGame[A-Z][A-Za-z0-9_]*")

WIDENS = {("float", "int")}
"""(parameter type, column type) pairs where the mismatch is deliberate.

`BehaviorParam.coerce` widens an int to a float, because Tiled writes `900`
for a float-typed property and calling that an authoring error would make
every whole-number float one. The reverse does NOT widen -- a float into an
int parameter raises -- so it is not symmetric and this set is not a pair of
sets.
"""


def catalogue_tokens(text: str) -> tuple[tuple[str, ...], tuple[str, ...]]:
    """(tokens with a section, tokens with a summary row) as the FILE has them.

    Two separate expressions render these in `describe_all`, so reading only
    one of them would let the other drift -- a behavior listed in the table
    and missing its section reads as documented right up until somebody
    scrolls.
    """
    return tuple(HEADING.findall(text)), tuple(SUMMARY_ROW.findall(text))


def documented_params(text: str) -> dict[str, tuple[str, ...]]:
    """behavior token -> the parameter keys its own section documents.

    Sliced by section rather than scanned whole: a parameter row belongs to
    the behavior whose heading precedes it, and a global scan would let a
    parameter documented under the wrong behavior pass.
    """
    found: dict[str, tuple[str, ...]] = {}
    marks = [(m.group(1), m.start()) for m in HEADING.finditer(text)]
    for index, (token, start) in enumerate(marks):
        end = marks[index + 1][1] if index + 1 < len(marks) else len(text)
        found[token] = tuple(PARAM_ROW.findall(text[start:end]))
    return found


def column_violations(registry, packs) -> list[str]:
    """Every actors column a behavior consumes that its genre does not declare.

    THE ASSERTION WITH TEETH. A behavior declaring
    `BehaviorParam("gravity", ..., source="actors")` is making a claim about
    the project's data model, and the claim is checkable: the pack it names in
    `genres` must have an `actors` table with a `gravity` column of a
    compatible type. Nothing else in the tree checks it -- nothing in
    `scripts/` reads `data/project/` at all, so the mismatch would surface as
    a parameter that silently took its default on every actor, forever.

    A `source="actors"` parameter on a behavior that declares NO genre is a
    violation too. `genres=()` means "any", and a column that any pack may or
    may not have is a column no pack is answerable for.
    """
    found: list[str] = []
    for spec in sorted(registry.values(), key=lambda s: s.name):
        actor_params = [p for p in spec.params if p.source == "actors"]
        if not actor_params:
            continue
        if not spec.genres:
            found.append(
                "behavior %r reads %s from the actors table but declares no "
                "genres, so no pack is answerable for the column(s). Add the "
                "genre id(s) to its BehaviorSpec."
                % (spec.name, ", ".join(repr(p.key) for p in actor_params)))
            continue
        for genre_id in spec.genres:
            pack = packs.get(genre_id)
            if pack is None:
                found.append(
                    "behavior %r declares genre %r, which is not a pack on "
                    "disk (%s)" % (spec.name, genre_id,
                                   ", ".join(sorted(packs)) or "none"))
                continue
            table = pack.table("actors")
            if table is None:
                found.append(
                    "behavior %r declares genre %r, whose pack has no 'actors' "
                    "table to read %s from"
                    % (spec.name, genre_id,
                       ", ".join(repr(p.key) for p in actor_params)))
                continue
            for param in actor_params:
                column = table.field(param.key)
                if column is None:
                    found.append(
                        "behavior %r consumes actors column %r, and genre %r "
                        "does not declare it. Add it to "
                        "editor/genres/%s/genre.json, or change the parameter "
                        "to source=\"object\"."
                        % (spec.name, param.key, genre_id, genre_id))
                elif (column.type != param.type
                      and (param.type, column.type) not in WIDENS):
                    found.append(
                        "behavior %r declares %r as %s and genre %r declares "
                        "that column as %s; an authored value would be refused "
                        "by BehaviorParam.coerce"
                        % (spec.name, param.key, param.type, genre_id,
                           column.type))
    return found


def spawn_violations(packs, registry=None) -> list[str]:
    """Every object class a pack allows that the spawn registry cannot build.

    `spawn_objects` RAISES on an unknown Type, so an object placed from a
    class the pack advertised makes the whole map unloadable -- and the editor
    validates placements against exactly this list, so the pack advertising a
    class the engine cannot build is the editor telling an author to break
    their map.
    """
    table = SPAWN_REGISTRY if registry is None else registry
    found: list[str] = []
    for pack in sorted(packs.values(), key=lambda p: p.id):
        for layer in pack.layers:
            for kind in layer.object_types:
                if kind not in table:
                    found.append(
                        "genre %r allows object class %r on layer %r, and it "
                        "is not in SPAWN_REGISTRY (%s), so an object of that "
                        "Type makes the map raise at load"
                        % (pack.id, kind, layer.name,
                           ", ".join(sorted(table)) or "empty"))
            for kind in layer.unique_types:
                if kind not in layer.object_types:
                    found.append(
                        "genre %r declares %r unique on layer %r without "
                        "allowing it there" % (pack.id, kind, layer.name))
    return found


def default_list_violations(packs, registry) -> list[str]:
    """Every class default a pack declares that would not actually work.

    Reads `GenreLayer.object_classes` -- the loaded field, not a second parse
    of the same JSON. Two readers of one file format is how a rule and the
    thing it judges drift apart.

    `editor/core/genre.py` already refuses, at pack load, everything the
    ENGINE would refuse: an unregistered token, a duplicate, a declared
    conflict, a class the layer forbids. What is left for a check is the two
    things `validate_list` structurally cannot see, because neither makes a
    map fail to load -- they make a placed object quietly not work:

      * a token gated to a DIFFERENT genre. `spec.genres` is reported by the
        behavior panel and enforced by nobody, so a platformer pack shipping
        `topdown_move` would load, materialise, attach, and not move.
      * a token whose status is not `live`. `_swap_section` already refuses
        to RECOMMEND one for exactly this reason; a pack default is a
        stronger claim than a recommendation, so it is held to the same bar.

    The unregistered-token clause is kept as well. It is unreachable through
    `genre.load` today and that is the point: it is what still catches a pack
    built any other way, and the day the loader's guard is loosened this is
    the assertion that goes red instead of the author's map.
    """
    found: list[str] = []
    for genre_id in sorted(packs):
        pack = packs[genre_id]
        for layer in pack.layers:
            for declared in layer.object_classes:
                for token in declared.behaviors:
                    spec = registry.get(token)
                    if spec is None:
                        found.append(
                            "genre %r gives object class %r the default "
                            "behavior %r, which is not registered (%s)"
                            % (genre_id, declared.type, token,
                               ", ".join(sorted(registry)) or "the registry "
                               "is empty"))
                        continue
                    if spec.genres and genre_id not in spec.genres:
                        found.append(
                            "genre %r gives object class %r the default "
                            "behavior %r, which declares genres %s -- it "
                            "would attach and do nothing"
                            % (genre_id, declared.type, token,
                               list(spec.genres)))
                    if spec.status != "live":
                        found.append(
                            "genre %r gives object class %r the default "
                            "behavior %r, whose status is %r -- a default is "
                            "a stronger claim than a recommendation, and "
                            "this one is not recommended either"
                            % (genre_id, declared.type, token, spec.status))
    return found


def vocabulary_violations(text: str, where: str, registry=None) -> list[str]:
    """Every `pyoneer_*` name in `text` that is not a real property name.

    This is the spelling guard extended to the prose. A property written into
    a .tmx under a name nothing reads does nothing at all and reports nothing
    (law 7), so a document that teaches `pyoneer_behaviours` (the British
    form, which
    the vocabulary does not use) is a document that teaches an author to write
    a dead property.
    """
    table = BEHAVIOR_REGISTRY if registry is None else registry
    # layer_profile.KNOWN covers what a LAYER or an OBJECT may declare.
    # `pyoneer_collision` is neither -- it sits on a <tileset> element and
    # names the .blitmask that tileset's tiles carry -- so it is imported from
    # the module that reads it rather than spelled again here.
    known = (set(layer_profile.KNOWN) | {BEHAVIORS, ACTOR}
             | {collision_runtime.DEFAULTS_PROPERTY})
    # The two bare prefixes are legal prose -- "the `pyoneer_` prefix is
    # load-bearing", "a stray `pyoneer_param_` nothing consumes" -- and are
    # not claims that a property by that name exists.
    prefixes = {layer_profile.PREFIX, PARAM_PREFIX}
    found: list[str] = []
    for name in sorted(set(PYONEER_NAME.findall(text))):
        if name in known or name in prefixes:
            continue
        if name.startswith(PARAM_PREFIX):
            suffix = name[len(PARAM_PREFIX):]
            if TOKEN.match(suffix):
                continue
            found.append(
                "%s writes %r, whose parameter key %r is not snake_case"
                % (where, name, suffix))
            continue
        found.append(
            "%s writes the property name %r, which is not one the engine "
            "reads. Known: %s, and %s<key>."
            % (where, name, ", ".join(sorted(known)), PARAM_PREFIX))
    return found


def rules_coverage_violations(text: str, genre_id: str, registry) -> list[str]:
    """Behaviors that claim this genre and are not named in its RULES.md.

    Only the genre-EXCLUSIVE ones. A behavior declaring `genres=()` applies
    everywhere and lives in the generated document; requiring every pack to
    restate the whole catalogue would rebuild in prose the thing that
    generation exists to stop. But a behavior that says *I am the platformer's
    body* and goes unmentioned in the platformer's rules is a behavior an AI
    reading that pack will not know to reach for -- which is the same failure
    as it not existing.
    """
    found: list[str] = []
    for spec in sorted(registry.values(), key=lambda s: s.name):
        if genre_id not in spec.genres:
            continue
        if ("`%s`" % spec.name) not in text:
            found.append(
                "behavior %r declares genre %r and %s/RULES.md never names it, "
                "so nothing reading that pack learns it exists"
                % (spec.name, genre_id, genre_id))
    return found


def missing_class_names(text: str, defined: set[str]) -> list[str]:
    """Every `Game*` class the text names that is not defined anywhere.

    A rules document that teaches a class name the tree does not have sends
    an AI to grep for it, find nothing, and invent one -- which is how a
    genre pack ends up prescribing a subclass in the same breath as telling
    you not to write subclasses.
    """
    return sorted({name for name in GAME_CLASS.findall(text)
                   if name not in defined})


def defined_names() -> set[str]:
    """Every class and function name defined under scripts/, editor/, config/.

    AST, not grep: a name in a docstring or a comment is not a definition, and
    counting one would make this rule pass for a class that only exists in
    prose -- which is the exact failure it is written to catch.
    """
    names: set[str] = set()
    roots = [os.path.join(ROOT, part) for part in ("scripts", "editor", "config")]
    roots.append(os.path.join(ROOT, "main.py"))
    for root in roots:
        walk = ([(os.path.dirname(root), [], [os.path.basename(root)])]
                if os.path.isfile(root) else os.walk(root))
        for dirpath, _dirs, files in walk:
            if "__pycache__" in dirpath:
                continue
            for name in files:
                if not name.endswith(".py"):
                    continue
                with open(os.path.join(dirpath, name), encoding="utf-8") as handle:
                    try:
                        tree = ast.parse(handle.read())
                    except SyntaxError:
                        continue
                for node in ast.walk(tree):
                    if isinstance(node, (ast.ClassDef, ast.FunctionDef)):
                        names.add(node.name)
    return names


# ===========================================================================
# What the engine has actually wired up. Derived by DRIVING it, never by
# reading a flag: a boolean somebody has to remember to flip is a boolean
# that is wrong on the commit that matters.
# ===========================================================================

class _ProbeEntity(GameEntity):
    """A GameEntity that is constructible. Filling the two abstract methods
    is the whole difference between the base class and something a check can
    stand up, and it needs no art."""

    def core_lifecycle_build(self, event=None):
        pass

    def core_input_receive(self, events=None):
        pass


class _Spy(EntityBehavior):
    """Counts the frames the drive gave it."""

    def __init__(self):
        self.calls = 0

    def update(self, entity, event):
        self.calls += 1


_SPY_SPEC = BehaviorSpec(name="probe_spy",
                         summary="Counts update calls. Never registered.",
                         factory=_Spy, order=50)


def drive_calls(frames: int, enabled: bool = True,
                entity_class=None) -> int | None:
    """How many times a bound behavior's `update` ran over `frames` frames.

    None when there is no `EntityBehaviors` on the entity to attach to at all,
    which is a different answer from zero: nothing to drive versus a drive
    that does not run.

    A COUNT rather than a boolean, and driven for a caller-chosen number of
    frames, because the two ways this wire breaks look identical to a
    single-frame yes/no probe: a drive that fires once at attach and never
    again returns 1 for any frame count, and a drive that fires twice per
    frame returns 2 for one frame. Only `calls == frames` for more than one
    value of `frames` separates them from a working one.

    `entity_class` is section 9's seam: an entity with no holder, a holder of
    the wrong type, a dead drive and a doubled one are all constructible from
    out here, so rows 1 and 2 are watched saying `no` without the engine being
    edited to make them.
    """
    entity = (_ProbeEntity if entity_class is None else entity_class)()
    holder = getattr(entity, HOLDER, None)
    if not isinstance(holder, EntityBehaviors):
        return None
    spy = _Spy()
    spy.spec = _SPY_SPEC
    holder.attach(spy)
    spy.enabled = enabled
    for _ in range(frames):
        entity.core_frame_update(PyoneerEvent(GameEventType.UPDATE,
                                              data={"delta": 1.0}))
    return spy.calls


def entity_drives_behaviors(entity_class=None) -> bool:
    """True when `GameEntity.core_frame_update` really runs a bound behavior."""
    return drive_calls(2, entity_class=entity_class) == 2


# ---------------------------------------------------------------------------
# THE SCANS -- "is this wire in the CODE", asked of the parse tree.
#
# Two of these measured something weaker than the column they filled, and both
# shapes had already been paid for next door. `_calls` matched a BARE spelling
# (`func.id` / `func.attr`) with no resolution through the import that brought
# the name in, so a module holding its own `read_requests` method read as the
# whole wire. `_assigns_collision_field` was a REGEX over source text, which is
# weaker still: measured on the real pattern, it counted a COMMENT, a DOCSTRING
# and `entity.collision_field == other` -- the first half of `==` satisfies it
# -- and it counted the renderer assigning its OWN slot, which is the one line
# whose deletion the column exists to report.
#
# Every scan below is driven BOTH ways by section 9 against a PLANTED source
# tree. A detector nobody has watched say `no` is a green word, not a
# measurement.
# ---------------------------------------------------------------------------

SKIP_DIRS = {".git", "__pycache__", ".venv", "docs", "data"}

HOLDER = "behaviors"
"""The attribute a constructed entity keeps its `EntityBehaviors` under.

Row 1's own title prints this name and row 4's attach scan matches
`<something>.behaviors.attach_all(...)` structurally, so the two rows agree
about what the holder is called by spelling it in exactly one place.
"""

ATTACH = EntityBehaviors.attach_all.__name__
READ = read_requests.__name__
"""Asked of the class and of the function rather than retyped: a rename moves
the scan with the thing, instead of quietly emptying it."""

BEHAVIOR_MODULES = (behavior_package.__name__, read_requests.__module__)
"""Both legal homes of the read: the package that re-exports it and the module
that defines it.

Asking the FUNCTION for its module alone -- the sibling instrument's rule --
would have matched none of the three real readers, because every one of them
imports from the package. A false negative is the safe direction to fail in
and it is still a wrong answer, so both are accepted and nothing else is.
"""

BEHAVIOR_DIR = behavior_package.__name__.replace(".", "/") + "/"
"""The package that DEFINES the read, excluded from every scan of its callers:
a function calling its own neighbour is not a production wire."""

COLLISION_FIELD = "collision_field"
PROBE_TYPE = "ProbeBody"

_TREES: dict = {}
_FILES: dict = {}
_SCANS: dict = {}
"""Parse and scan caches for the REAL tree only -- never for a planted world.

Section 9 drives `integration_rows` a few dozen times and every call that
plants nothing re-walks `scripts/` and `main.py`. Nothing in this process
writes a `.py`, so a tree parsed once is the tree for the whole run.
"""


def _cached(key, hits, sources):
    """One scan's answer, remembered only when it came from the REAL tree."""
    out = tuple(sorted(set(hits)))
    if sources is None:
        _SCANS[key] = out
    return out


def python_files(*roots, sources=None) -> tuple[str, ...]:
    """Every `.py` under `roots`, repo-relative, forward slashes, sorted.

    A root is a directory OR a single `.py` file: `main.py` is the game's boot
    and belongs to no package, and a walker that took directories only could
    not see the one file some of these rows describe.

    `sources` replaces the tree with a `{repo/relative/path.py: source}`
    mapping, which is how section 9 hands every scan a world where the wire is
    planted broken without touching a tracked file. The roots still apply to
    it, which is the point: a decoy under `scripts/game/` must not answer a
    scan of `scripts/loaders/`.
    """
    if sources is not None:
        return tuple(sorted(
            rel for rel in sources
            if any(rel == root or rel.startswith(root.rstrip("/") + "/")
                   for root in roots)))
    if roots in _FILES:
        return _FILES[roots]
    found: list[str] = []
    for root in roots:
        base = os.path.join(ROOT, root)
        if os.path.isfile(base) and base.endswith(".py"):
            found.append(os.path.relpath(base, ROOT).replace(os.sep, "/"))
            continue
        for folder, dirs, names in os.walk(base):
            dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS)
            for name in sorted(names):
                if name.endswith(".py"):
                    found.append(
                        os.path.relpath(os.path.join(folder, name),
                                        ROOT).replace(os.sep, "/"))
    _FILES[roots] = tuple(sorted(found))
    return _FILES[roots]


def _tree(rel, sources=None):
    if sources is not None:
        return ast.parse(sources[rel])
    if rel not in _TREES:
        with open(os.path.join(ROOT, rel), encoding="utf-8",
                  errors="replace") as handle:
            _TREES[rel] = ast.parse(handle.read())
    return _TREES[rel]


def _dotted(node):
    """`a.b.c` written out, or None for anything that is not a plain name."""
    parts = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if not isinstance(node, ast.Name):
        return None
    parts.append(node.id)
    return ".".join(reversed(parts))


def _spellings(tree, modules, wanted) -> set[str]:
    """Every way THIS file could spell one of `wanted` and mean one of `modules`.

    Three import shapes, three bindings: `import a.b.c` binds the dotted path
    (`a.b.c.NAME`), `from a.b import c` binds the module under one name
    (`c.NAME`, or its alias), and `from a.b.c import NAME` binds the attribute
    itself (a bare `NAME`, or its alias). Nothing else counts, and a star
    import binds nothing this can name.

    That is the direction to fail in: a row saying `no` for a wire that exists
    sends somebody to look, while a row saying `yes` for a wire that does not
    is the defect this whole table is the instrument against.
    """
    out: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name in modules:
                    out |= {"%s.%s" % (alias.asname or alias.name, w)
                            for w in wanted}
        elif isinstance(node, ast.ImportFrom):
            for alias in node.names:
                if node.module in modules and alias.name in wanted:
                    out.add(alias.asname or alias.name)
                elif "%s.%s" % (node.module or "", alias.name) in modules:
                    out |= {"%s.%s" % (alias.asname or alias.name, w)
                            for w in wanted}
    return out


def calls_through(name, modules, *roots, sources=None, skip=None):
    """Files under `roots` that CALL `name` THROUGH an import of `modules`.

    The parse tree, not the text, and the import, not the spelling. Both
    distinctions are paid for here: `read_requests` is named in three
    docstrings under `scripts/`, and a module holding its own method by that
    name is not a module that reads a map's behavior list. Counting either
    reports a wire that is not there, which is the one thing this table must
    never do.
    """
    key = ("calls", name, modules, roots, skip)
    if sources is None and key in _SCANS:
        return _SCANS[key]
    hits: list[str] = []
    for rel in python_files(*roots, sources=sources):
        if skip and rel.startswith(skip):
            continue
        tree = _tree(rel, sources=sources)
        spellings = _spellings(tree, modules, (name,))
        if not spellings:
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Call) and _dotted(node.func) in spellings:
                hits.append(rel)
                break
    return _cached(key, hits, sources)


def attach_calls(*roots, sources=None, skip=None):
    """Files that call `<something>.behaviors.attach_all(...)`.

    ROW 4'S MISSING HALF. The row says a declaration is turned into ATTACHED
    behaviors and the scan measured only the read, so deleting every
    `attach_all` call in the engine left it green while nothing was ever
    attached to anything.

    Matched structurally rather than by name: the call must be `attach_all` on
    an attribute called `behaviors`, so a module with an unrelated
    `self.attach_all(...)` of its own is not mistaken for the drive's holder.
    """
    key = ("attach", roots, skip)
    if sources is None and key in _SCANS:
        return _SCANS[key]
    hits: list[str] = []
    for rel in python_files(*roots, sources=sources):
        if skip and rel.startswith(skip):
            continue
        for node in ast.walk(_tree(rel, sources=sources)):
            func = node.func if isinstance(node, ast.Call) else None
            if (isinstance(func, ast.Attribute) and func.attr == ATTACH
                    and isinstance(func.value, ast.Attribute)
                    and func.value.attr == HOLDER):
                hits.append(rel)
                break
    return _cached(key, hits, sources)


def _assigned_attributes(node):
    """Every attribute an assignment STATEMENT writes, tuple targets included.

    `ast.AnnAssign` is deliberately absent: an annotated declaration is not an
    assignment of a field, so `self.collision_field: CollisionField | None =
    None` does not count itself as its own consumer. That was true of the
    regex this replaces as well, and it is the one property of it worth
    keeping.
    """
    if isinstance(node, ast.Assign):
        targets = list(node.targets)
    elif isinstance(node, ast.AugAssign):
        targets = [node.target]
    else:
        return
    while targets:
        target = targets.pop()
        if isinstance(target, (ast.Tuple, ast.List)):
            targets.extend(target.elts)
        elif isinstance(target, ast.Starred):
            targets.append(target.value)
        elif isinstance(target, ast.Attribute):
            yield target


def _writes_field(tree, attr) -> bool:
    """True when this file assigns SOMEONE ELSE'S `.<attr>`."""
    for node in ast.walk(tree):
        for target in _assigned_attributes(node):
            if target.attr != attr:
                continue
            owner = target.value
            if isinstance(owner, ast.Name) and owner.id in ("self", "cls"):
                continue
            return True
    return False


def assigns_field(attr, *roots, sources=None):
    """Files that hand ANOTHER object a `.<attr>`, from the parse tree.

    Four separate weaknesses of the regex this replaces, all four measured on
    it: it counted a COMMENT; it counted a DOCSTRING; it counted
    `entity.collision_field == other`, because the first half of `==` is an
    `=`; and it counted `self.collision_field = ...`.

    The last one is not a nicety. `LayerRenderer` keeps a field of its own
    under that name, so deleting the ONE line that hands it to an entity --
    `entity.collision_field = self.collision_field` -- left the row saying
    **yes** with every body in the game ungated, which is precisely the
    failure the row's own cost text describes.

    DECLARED BLINDNESS: an entity class assigning its OWN `self.collision_field`
    in production would read `no` here. That is the price of telling the
    renderer's private slot apart from the hand-out; it is the safe direction
    to be wrong in, and section 9 pins it as a case rather than leaving it to
    be discovered.
    """
    key = ("assigns", attr, roots)
    if sources is None and key in _SCANS:
        return _SCANS[key]
    hits = [rel for rel in python_files(*roots, sources=sources)
            if _writes_field(_tree(rel, sources=sources), attr)]
    return _cached(key, hits, sources)


# ---------------------------------------------------------------------------
# The spawn drive. A scan can prove a production module CALLS the read; only a
# drive can prove the OBJECT'S OWN properties are what reaches it.
# ---------------------------------------------------------------------------

_SPAWN_TMX = """<?xml version="1.0" encoding="UTF-8"?>
<map version="1.10" orientation="orthogonal" renderorder="right-down" \
width="4" height="4" tilewidth="16" tileheight="16" infinite="0" \
nextlayerid="3" nextobjectid="3">
 <objectgroup id="2" name="entity">
  <object id="1" name="body" type="%s" x="0" y="16" width="16" height="16">
   <properties>
    <property name="%s" value="%s"/>
   </properties>
  </object>
 </objectgroup>
</map>
"""

_TMP = tempfile.TemporaryDirectory(prefix="pyoneer_behavior_docs_")


def _spawn_fixture(token: str) -> str:
    """A four-cell map carrying ONE object that declares ONE behavior.

    LAW 4: this check's own fixture, written here and deleted with the run.
    A row measured over `data/maps/starter.tmx` would report what somebody
    authored rather than what the loader does with what it is given.
    """
    path = os.path.join(_TMP.name, "declares.tmx")
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(_SPAWN_TMX % (PROBE_TYPE, BEHAVIORS, token))
    return path


def declaration_reaches_spawn(reader=None) -> bool:
    """Does a tmx object's `pyoneer_behaviors` REALLY reach a spawn record?

    DRIVEN, not scanned, and this is the sibling instrument's lesson applied a
    row early: a detector that reads a FILE reports what was AUTHORED, one that
    runs the code reports what RUNS. The scan beside this cannot tell
    `read_requests(obj.properties)` from `read_requests({})`, and it cannot
    tell either from a spawn path that attaches a fixed list of its own -- all
    three read identically, and two of them mean the authored list does
    nothing.

    So: write a map with one object declaring one token, run the real
    `spawn_objects` over it with a registry of this check's own, and assert the
    RECORD carries the token the object declared and nothing else.

    `reader` replaces `map_loader`'s own `read_requests` for the length of one
    call, which is how section 9 breaks the engine without editing it.
    """
    if not BEHAVIOR_REGISTRY:
        return False
    token = sorted(BEHAVIOR_REGISTRY)[0]
    original = map_loader.read_requests
    if reader is not None:
        map_loader.read_requests = reader
    try:
        records = map_loader.spawn_objects(_spawn_fixture(token),
                                           {PROBE_TYPE: _ProbeEntity})
        got = [tuple(request.spec.name for request in record.behaviors)
               for record in records]
    except Exception:                                      # noqa: BLE001
        return False
    finally:
        map_loader.read_requests = original
    return got == [(token,)]


def input_actions(config=None, manager=None) -> tuple[tuple[str, ...],
                                                      tuple[str, ...]]:
    """(verbs a REAL `InputActionManager` holds, verbs the LOADER dropped).

    THE ONE ROW IN THIS TABLE THAT MEASURED A FILE. It read `config/inputs.json`
    with `json.load` and reported the key set, so the cell printed **yes** for a
    verb that the loader never registered -- and an unregistered verb is exactly
    the failure the row exists to warn about, because `held()` is an unguarded
    dict index that raises inside `core_frame_update` and kills the frame for
    every sibling in the scene bucket (law 10).

    The sibling instrument next door, `tools/check_event_docs.py`, had two rows
    of that shape and both were repaired in the pass before this one: the fix
    there was to LOAD the thing rather than parse the file beside it. This is
    the same fix. `prepare_inputs` is what the boot calls, `validate_bindings`
    runs inside it, and a binding the loader refuses now takes the row to `no`
    where it used to be reported as a working wire.

    The file is still opened, for one reason: to tell "the author declared no
    `jump`" apart from "the author declared one and the LOADER dropped it",
    which is the difference between an authoring gap and a broken engine. The
    second is reported in the cell, and it is the second tuple returned here.

    `config` and `manager` are section 9's seams -- a synthesised binding table
    and a planted loader -- so both answers are DRIVEN rather than hoped for.
    """
    if config is None:
        with open(INPUTS_PATH, encoding="utf-8") as handle:
            config = json.load(handle)
    build_manager = InputActionManager if manager is None else manager
    try:
        loaded = tuple(sorted(
            build_manager().prepare_inputs(dict(config)).actions))
    except Exception:                                      # noqa: BLE001
        # A refusal here is the loader doing its job loudly, and it means no
        # verb is pollable at all -- so the honest answer is the empty tuple.
        return (), ()
    return loaded, tuple(name for name in sorted(config) if name not in loaded)


def integration_rows(registry=None, *, sources=None, entity_class=None,
                     config=None, manager=None,
                     reader=None) -> list[tuple[str, bool, str]]:
    """(what the wire is, whether it exists, what it would cost) -- all derived.

    EVERY SEAM THIS READS IS AN ARGUMENT, and section 9 drives each one with
    the code planted BROKEN: an entity with no holder, an entity whose drive
    never fires, an empty registry, a decoy source tree, a spawn whose reader
    ignores the object it was handed, a binding table the loader refuses.

    Two rows are CONJUNCTIONS of a scan and a drive, and both halves have to
    hold. A scan proves a production module calls the read; only a drive
    proves the object's own properties are what reaches it, and only a second
    scan proves anything ever attaches what was read. A row that is one half
    of its own claim is law 5's vacuous assertion wearing a table cell.
    """
    table = BEHAVIOR_REGISTRY if registry is None else registry
    entity = (_ProbeEntity if entity_class is None else entity_class)()
    has_holder = isinstance(getattr(entity, HOLDER, None), EntityBehaviors)
    readers = calls_through(READ, BEHAVIOR_MODULES, "scripts", "main.py",
                            sources=sources, skip=BEHAVIOR_DIR)
    attached = attach_calls("scripts", "main.py", sources=sources,
                            skip=BEHAVIOR_DIR)
    spawners = calls_through(READ, BEHAVIOR_MODULES, "scripts/loaders",
                             "scripts/core", sources=sources,
                             skip=BEHAVIOR_DIR)
    reaches = declaration_reaches_spawn(reader=reader)
    gated = assigns_field(COLLISION_FIELD, "main.py", "scripts",
                          sources=sources)
    actions, dropped = input_actions(config=config, manager=manager)
    return [
        ("`GameEntity.%s` exists on a constructed entity" % HOLDER,
         has_holder,
         "one attribute in `GameEntity.__init__`"),
        ("`GameEntity.core_frame_update` runs the drive",
         entity_drives_behaviors(entity_class=entity_class),
         "one line replacing the `pass` in `game_entity.py`"),
        ("a behavior is registered",
         bool(table),
         "one `register(BehaviorSpec(...))` in "
         "`scripts/game/behavior/registry.py`"),
        ("a declaration is turned into attached behaviors somewhere",
         bool(readers) and bool(attached),
         # BOTH HALVES ARE PRINTED, because both halves are measured. The
         # cell used to name the READERS alone and call that "done in",
         # which left the attach site -- the half whose disappearance now
         # turns this row `no` -- unnamed anywhere in the document. A
         # reader chasing "where does my list actually get attached" was
         # sent to `map_loader.py`, which only fills a `SpawnedEntity`.
         ("read in " + ", ".join("`%s`" % r for r in readers)
          + ", attached in " + ", ".join("`%s`" % a for a in attached))
         if readers and attached else
         ("`%s` + `build` + `%s`" % (READ, ATTACH)
          + ("" if not readers else
             "; the read is done in %s and NOTHING in production calls "
             "`.%s.%s`, so every list read is then dropped on the floor"
             % (", ".join("`%s`" % r for r in readers), HOLDER, ATTACH)))),
        ("a **tmx object's** `%s` property is read when it spawns" % BEHAVIORS,
         bool(spawners) and reaches,
         "`read_requests(obj.properties)` in `scripts/loaders/map_loader.py`, "
         "carried on `SpawnedEntity` and attached by the binder. Until then a "
         "list authored in Tiled does nothing and only a Python caller can "
         "compose one." if not (spawners and reaches) else
         "read in " + ", ".join("`%s`" % s for s in spawners)),
        ("`GameEntity.%s` is assigned in production" % COLLISION_FIELD,
         bool(gated),
         "`field_from_map` at map load, handed to each spawned entity. Until "
         "then every body is UNGATED -- a platformer body accelerates "
         "downward forever and never lands."
         if not gated else "assigned in " + ", ".join("`%s`" % g for g in gated)),
        ("a `jump` input action exists",
         "jump" in actions,
         ("`config/inputs.json` declares `jump` and the loader did NOT "
          "register it, so polling the verb raises inside the frame -- that "
          "is an engine defect, not a missing binding"
          if "jump" in dropped else
          "one entry in `config/inputs.json`; `held()`/`pressed()` are "
          "unguarded dict indexes, so the behavior and the binding are ONE "
          "change") if "jump" not in actions else
         "`prepare_inputs` registered " + ", ".join("`%s`" % a
                                                    for a in actions)),
    ]


# ===========================================================================
# The generator
# ===========================================================================

def _genre_section(packs) -> list[str]:
    lines = ["## What each genre pack declares", "",
             "Derived from `editor/genres/*/genre.json`, so a pack that gains "
             "a column gains it here. A behavior whose parameter declares "
             "`source=\"actors\"` may name any column in its genre's table "
             "below -- and only those, which is what this check enforces.", ""]
    for genre_id in sorted(packs):
        pack = packs[genre_id]
        lines.append("### `%s` -- %s" % (genre_id, pack.title))
        lines.append("")
        gated = [l.name for l in pack.layers if l.collision]
        lines.append("- **passability is authored against** %s"
                     % (", ".join("`%s` (companion `%sCollision`)" % (n, n)
                                  for n in gated) or "no layer"))
        for layer in pack.layers:
            if layer.kind != "object":
                continue
            lines.append("- **object layer `%s` allows** %s"
                         % (layer.name,
                            ", ".join("`%s`" % t for t in layer.object_types)
                            or "nothing"))
        actors = pack.table("actors")
        if actors is None:
            lines.append("- **no `actors` table**, so no `source=\"actors\"` "
                         "parameter can resolve here")
        else:
            lines.append("- **actors columns a parameter may name** %s"
                         % ", ".join("`%s` (%s)" % (f.name, f.type)
                                     for f in actors.fields))
        defaults = []
        for layer in pack.layers:
            for declared in layer.object_classes:
                defaults.append("`%s` on `%s` -> `%s`"
                                % (declared.type, layer.name,
                                   declared.behaviors_text or "nothing"))
        if defaults:
            lines.append(
                "- **default behavior lists** %s. The editor MATERIALISES "
                "these into the object's `%s` property when the object is "
                "added, so the `.tmx` stays the whole truth and the engine "
                "never has to read a pack -- `scripts/` may not import "
                "`editor/`. It is a STARTING VALUE, not a policy: edit the "
                "list on the object afterwards and your edit stands, because "
                "nothing reads the pack again."
                % (", ".join(defaults), BEHAVIORS))
        else:
            lines.append(
                "- **default behavior lists** none declared. The pack may "
                "declare them as `layers[].object_classes[].behaviors`; the "
                "editor MATERIALISES such a default into the object when the "
                "object is added, so the `.tmx` stays the whole truth and the "
                "engine never has to read a pack -- `scripts/` may not import "
                "`editor/`.")
        lines.append("")
    return lines


def _swap_section(registry) -> list[str]:
    lines = ["## Swapping one behavior list for another", "",
             "This is the whole point of the design: the same class, the same "
             "spawn entry, a different list.", ""]
    if not registry:
        lines.append(
            "There is nothing to swap yet -- the registry is empty, so every "
            "token below would raise `PyoneerAssetMissingError`. The shape it "
            "will take, with the tokens left as placeholders on purpose:")
        lines.append("")
        lines.append("```xml")
        lines.append('<object id="1" type="GamePlayer" x="64" y="96">')
        lines.append("  <properties>")
        lines.append('    <property name="%s" value="&lt;move&gt;,&lt;collide&gt;"/>'
                     % BEHAVIORS)
        lines.append('    <property name="%smove_speed" type="int" value="24"/>'
                     % PARAM_PREFIX)
        lines.append("  </properties>")
        lines.append("</object>")
        lines.append("```")
        lines.append("")
        lines.append(
            "Change the value of `%s` and the object plays differently with "
            "no code change and no new class. Nothing else about the object "
            "moves: same `type`, same `SPAWN_REGISTRY` entry, same depth."
            % BEHAVIORS)
        lines.append("")
        return lines
    ordered = sorted(registry.values(), key=lambda s: (s.order, s.name))
    neutral = [s.name for s in ordered if not s.genres]
    claimed = sorted({g for s in ordered for g in s.genres})
    lines.append("| genre | a complete, legal list |")
    lines.append("| --- | --- |")
    for genre_id in claimed:
        chosen: list[str] = []
        for spec in ordered:
            if spec.genres and genre_id not in spec.genres:
                continue
            # This column is read as a RECOMMENDATION, so it may only offer
            # what works out of the box. A `needs-host` behavior runs
            # correctly and still does nothing until the game assigns
            # something the engine never will -- and `requires` is reported,
            # never enforced, so there is no crash to reveal the mistake.
            # `authoring-only` is excluded for the plainer reason.
            if spec.status != "live":
                continue
            # Legality is decided by the engine's own rule, not by a second
            # copy of it here: a candidate is accepted only if `validate_list`
            # accepts the list it would produce. That is what keeps this table
            # from ever printing a pair the loader would refuse.
            try:
                validate_list(chosen + [spec.name], registry)
            except Exception:                              # declared conflict
                continue
            chosen.append(spec.name)
        lines.append("| `%s` | `%s` |" % (genre_id, format_list(chosen)))
    lines.append("")
    lines.append("Set the object's `%s` property to one of those values. Same "
                 "`type`, same `SPAWN_REGISTRY` entry, same depth, same class "
                 "-- only the list changes. %s"
                 % (BEHAVIORS,
                    ("%s declare no genre and so belong in any list."
                     % ", ".join("`%s`" % n for n in neutral))
                    if neutral else ""))
    lines.append("")
    return lines


def render_doc(registry=None, packs=None) -> str:
    """The whole of `docs/BEHAVIORS.md`, from the registry and the packs.

    `describe_all()` first and verbatim, so the half the engine owns is not
    paraphrased anywhere. Then the two things it cannot see: what the engine
    around it has wired, and what the packs declare.
    """
    registry = BEHAVIOR_REGISTRY if registry is None else registry
    if packs is None:
        packs = load_packs()
    lines = [describe_all(registry).rstrip("\n"), "", SENTINEL, ""]
    lines.append("## Integration status")
    lines.append("")
    rows = integration_rows()
    lines.append(WIRED if all(ok for _, ok, _ in rows[:2]) else UNWIRED)
    lines.append("")
    lines.append(
        "Every row below is measured, not declared: the drive row is produced "
        "by constructing a real `GameEntity`, attaching a behavior and running "
        "two frames. A row that says *no* is a wire that does not exist, not a "
        "wire that is merely undocumented.")
    lines.append("")
    lines.append("| the wire | at this commit | what it takes |")
    lines.append("| --- | --- | --- |")
    for what, ok, cost in rows:
        lines.append("| %s | %s | %s |" % (what, "**yes**" if ok else "no", cost))
    lines.append("")
    lines.extend(_genre_section(packs))
    lines.extend(_swap_section(registry))
    return "\n".join(lines).rstrip("\n") + "\n"


def load_packs():
    """id -> GenrePack, for every pack on disk.

    The loaded pack only, never the raw `genre.json` beside it: a file format
    with two readers in one process is the shape that lets a rule and its
    subject disagree.
    """
    return {genre_id: genre_module.load(genre_id)
            for genre_id in genre_module.available()}


# ===========================================================================
# Fixtures. Deliberately wrong, so a rule that cannot fail is visible here.
# ===========================================================================

class _Move(EntityBehavior):
    def __init__(self, gravity: float = 900.0):
        self.gravity = gravity

    def update(self, entity, event):
        pass


def _param(key, type_, default, source="actors"):
    return BehaviorParam(key, key.replace("_", " "), type_, default,
                         "Fixture.", source=source)


def _spec(name, params=(), genres=("platformer",), **kw):
    return BehaviorSpec(name=name, summary="Fixture.", factory=_Move,
                        params=tuple(params), genres=tuple(genres), **kw)


def _fixture_pack(genre_id="fixture", columns=(("gravity", "float"),),
                  object_types=("GamePlayer",)):
    return GenrePack(
        id=genre_id, title="Fixture", summary="", root="",
        layers=(GenreLayer(name="entity", kind="object",
                           object_types=tuple(object_types),
                           unique_types=()),),
        tables=(GenreTable(name="actors", title="Actors",
                           fields=tuple(GenreField(name=n, type=t)
                                        for n, t in columns)),))


PACKS = load_packs()
DEFINED = defined_names()

print("check_behavior_docs -- the paper must agree with the machinery")
print(f"  registry: {len(BEHAVIOR_REGISTRY)} behavior(s); "
      f"packs: {', '.join(sorted(PACKS))}")


if "--write" in sys.argv:
    with open(DOC_PATH, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(render_doc(BEHAVIOR_REGISTRY, PACKS))
    print(f"\nwrote {os.path.relpath(DOC_PATH, ROOT)} "
          f"({len(BEHAVIOR_REGISTRY)} behavior(s))")
    raise SystemExit(0)


DOC_EXISTS = os.path.isfile(DOC_PATH)
DOC = ""
if DOC_EXISTS:
    with open(DOC_PATH, encoding="utf-8", newline="") as handle:
        DOC = handle.read().replace("\r\n", "\n")


# ===========================================================================
print("\n1. docs/BEHAVIORS.md is exactly what the generator produces")
# ===========================================================================
expect_true("the file exists at all", DOC_EXISTS)
expect_true("its first half is byte-for-byte registry.describe_all()",
            DOC.startswith(describe_all(BEHAVIOR_REGISTRY).rstrip("\n")))
expect("...and the whole file matches the generator",
       DOC, render_doc(BEHAVIOR_REGISTRY, PACKS))
expect("the boundary between the two halves is marked exactly once",
       DOC.count(SENTINEL), 1)
# Not implied by the equality above, unlike the count: if `describe_all` ever
# emitted this marker itself the boundary would be ambiguous and the prefix
# assertion would be reading the wrong half of the file.
expect("...and the generated half never emits the marker itself",
       describe_all(BEHAVIOR_REGISTRY).count(SENTINEL), 0)
expect_true("the file names the command that regenerates it",
            REGENERATE in DOC)


# ===========================================================================
print("\n2. the catalogue in the FILE names exactly the registered behaviors")
# ===========================================================================
_sections, _rows = catalogue_tokens(DOC)
expect("every behavior with a section is registered, and vice versa",
       sorted(_sections), sorted(BEHAVIOR_REGISTRY))
expect("...and the summary table lists the same set",
       sorted(_rows), sorted(BEHAVIOR_REGISTRY))
expect("no behavior is listed twice", len(set(_sections)), len(_sections))

# TEETH: the two assertions above pass for as long as the live document is
# correct, and say nothing about the reader. Drive the same function over a
# fixture registry, and over a document damaged in each of the two ways.
_fix_registry = {"zzz_late": _spec("zzz_late", order=90),
                 "aaa_early": _spec("aaa_early", order=10)}
_fix_doc = render_doc(_fix_registry, PACKS)
_fs, _fr = catalogue_tokens(_fix_doc)
expect("fixture: a populated registry produces a section per behavior",
       sorted(_fs), ["aaa_early", "zzz_late"])
expect("fixture: ...and a summary row per behavior", sorted(_fr),
       ["aaa_early", "zzz_late"])
expect("fixture: a doc missing one section is detected",
       sorted(catalogue_tokens(_fix_doc.replace("### `zzz_late`", "### zzz"))[0]),
       ["aaa_early"])
expect("fixture: a doc missing one summary row is detected",
       sorted(catalogue_tokens(_fix_doc.replace("| `zzz_late` | 90",
                                                "| zzz | 90"))[1]),
       ["aaa_early"])
# Order, not just membership: `aaa_early` (order 10) must print before
# `zzz_late` (order 90), which alphabetical order agrees with -- so the probe
# also runs the reverse pair, where it does not.
expect("fixture: the catalogue is in declared order, not alphabetical",
       list(catalogue_tokens(render_doc(
           {"aaa_late": _spec("aaa_late", order=90),
            "zzz_early": _spec("zzz_early", order=10)}, PACKS))[0]),
       ["zzz_early", "aaa_late"])


# ===========================================================================
print("\n3. every parameter the file documents is one its behavior declares")
# ===========================================================================
for _token, _keys in documented_params(DOC).items():
    expect(f"{_token}: documented parameters are the declared ones",
           sorted(_keys), sorted(BEHAVIOR_REGISTRY[_token].param_keys))

# TWO behaviors with DIFFERENT parameters, because a reader that scans the
# whole document instead of one section still answers correctly when there is
# only one section to confuse it with. `early` must not be credited with
# `late`'s parameter, and it is the only probe that can tell the two readers
# apart.
_pdoc = render_doc(
    {"early": _spec("early", (_param("gravity", "float", 900.0),), order=10),
     "late": _spec("late", (_param("hop", "int", 3, "object"),), order=90)},
    PACKS)
expect("fixture: a behavior's parameters are documented under its own heading",
       sorted(documented_params(_pdoc)["early"]), ["gravity"])
expect("fixture: a later behavior's parameter is not credited to an earlier one",
       sorted(documented_params(_pdoc)["late"]), ["hop"])
expect("fixture: a parameter under the WRONG heading is not credited",
       documented_params(_pdoc.replace("### `early`", "### `other`")).get("early"),
       None)


# ===========================================================================
print("\n4. every actors column a behavior consumes is declared by its genre")
# ===========================================================================
expect("the live registry against the real packs: nothing unbacked",
       column_violations(BEHAVIOR_REGISTRY, PACKS), [])

# TEETH. The line above compares [] with [] for as long as the live tree is
# clean, which is every day until it is not. Each fixture below violates
# exactly one clause.
expect("fixture: a column the genre DOES declare is clean",
       column_violations({"g": _spec("g", (_param("gravity", "float", 900.0),),
                                     genres=("platformer",))}, PACKS), [])
expect_reports(
    "fixture: the same column against a genre that lacks it is reported",
    column_violations({"g": _spec("g", (_param("gravity", "float", 900.0),),
                                  genres=("topdown_rpg",))}, PACKS),
    "'g'", "'gravity'", "'topdown_rpg'", "genre.json")
expect("fixture: a source=\"object\" parameter needs no column at all",
       column_violations({"g": _spec("g", (_param("nowhere", "int", 1, "object"),),
                                     genres=("topdown_rpg",))}, PACKS), [])
expect_reports(
    "fixture: an int parameter over a float column is a refused coercion",
    column_violations({"g": _spec("g", (_param("gravity", "int", 900),),
                                  genres=("platformer",))}, PACKS),
    "'gravity'", "int", "float")
expect("fixture: a float parameter over an int column widens, as coerce does",
       column_violations({"g": _spec("g", (_param("coyote_ms", "float", 90.0),),
                                     genres=("platformer",))}, PACKS), [])
expect_reports(
    "fixture: a genre id with no pack on disk is reported",
    column_violations({"g": _spec("g", (_param("gravity", "float", 900.0),),
                                  genres=("shmup",))}, PACKS),
    "'g'", "'shmup'", "not a pack on disk")
expect_reports(
    "fixture: an actors parameter with no declared genre is reported",
    column_violations({"g": _spec("g", (_param("gravity", "float", 900.0),),
                                  genres=())}, PACKS),
    "'g'", "'gravity'", "declares no genres")
expect("fixture: a behavior with no actors parameters needs no genre",
       column_violations({"g": _spec("g", (_param("x", "int", 1, "object"),),
                                     genres=())}, PACKS), [])
expect_reports(
    "fixture: a genre whose pack has no actors table is reported",
    column_violations(
        {"g": _spec("g", (_param("gravity", "float", 900.0),),
                    genres=("fixture",))},
        {"fixture": GenrePack(id="fixture", title="F", summary="", root="")}),
    "'g'", "no 'actors' table")


# ===========================================================================
print("\n5. a pack's object_types are all spawnable")
# ===========================================================================
expect("the real packs advertise only classes SPAWN_REGISTRY can build",
       spawn_violations(PACKS), [])
expect_reports(
    "fixture: a class the registry cannot build is reported",
    spawn_violations({"f": _fixture_pack(object_types=("GameFloorEntity",))}),
    "'fixture'", "'GameFloorEntity'", "raise at load")
expect("fixture: a class it CAN build is clean",
       spawn_violations({"f": _fixture_pack(object_types=("GamePlayer",))}), [])
expect_reports(
    "fixture: a unique class the layer does not allow is reported",
    spawn_violations({"f": GenrePack(
        id="f", title="F", summary="", root="",
        layers=(GenreLayer(name="entity", kind="object",
                           object_types=("GamePlayer",),
                           unique_types=("GameScene",)),))}),
    "'f'", "'GameScene'", "without allowing it")

# The fixtures below build `GenrePack` objects DIRECTLY rather than going
# through `genre.load`, and that is deliberate: `editor/core/genre.py` refuses
# an unregistered token at load, so a pack loaded from disk can no longer carry
# one. Bypassing the loader is the only way to prove this rule still bites --
# and it is exactly the case it exists for, since the loader's guard is one
# edit away from being loosened.
def _default_pack(genre_id="f", behaviors=(), object_type="GamePlayer"):
    return GenrePack(
        id=genre_id, title="F", summary="", root="",
        layers=(GenreLayer(
            name="entity", kind="object", object_types=("GamePlayer",),
            object_classes=(GenreObjectClass(type=object_type,
                                             behaviors=tuple(behaviors)),)),))


expect("no pack declares a default behavior list it cannot resolve",
       default_list_violations(PACKS, BEHAVIOR_REGISTRY), [])
expect("the real packs' defaults are not empty, so that line means something",
       sorted(c.type for p in PACKS.values() for l in p.layers
              for c in l.object_classes), ["GamePlayer", "GamePlayer"])
expect_reports(
    "fixture: a declared default naming an unregistered token is reported",
    default_list_violations({"f": _default_pack(behaviors=("ghost_move",))},
                            BEHAVIOR_REGISTRY),
    "'f'", "'ghost_move'", "not registered")
expect("fixture: a declared default naming a REGISTERED token is clean",
       default_list_violations({"f": _default_pack(behaviors=("real",))},
                               {"real": _spec("real", genres=())}), [])
expect_reports(
    "fixture: a default gated to ANOTHER genre is reported -- it would "
    "attach and silently do nothing",
    default_list_violations({"f": _default_pack(behaviors=("real",))},
                            {"real": _spec("real", genres=("other",))}),
    "'f'", "'real'", "would attach and do nothing")
expect("fixture: the same token under the genre it declares is clean",
       default_list_violations({"f": _default_pack(behaviors=("real",))},
                               {"real": _spec("real", genres=("f",))}), [])
expect_reports(
    "fixture: a default whose spec is not live is reported",
    default_list_violations({"f": _default_pack(behaviors=("real",))},
                            {"real": _spec("real", genres=(),
                                           status="authoring-only")}),
    "'f'", "'real'", "'authoring-only'")
expect("fixture: a pack with no object_classes at all reports nothing",
       default_list_violations(
           {"f": GenrePack(id="f", title="F", summary="", root="",
                           layers=(GenreLayer(name="entity", kind="object"),))},
           BEHAVIOR_REGISTRY), [])


# ===========================================================================
print("\n6. every pyoneer_* name in the docs is a real property name")
# ===========================================================================
RULES = {}
for _id in sorted(PACKS):
    _path = os.path.join(GENRES_DIR, _id, "RULES.md")
    with open(_path, encoding="utf-8", newline="") as handle:
        RULES[_id] = handle.read().replace("\r\n", "\n")

expect("docs/BEHAVIORS.md spells every property name correctly",
       vocabulary_violations(DOC, "BEHAVIORS.md"), [])
for _id, _text in RULES.items():
    expect(f"{_id}/RULES.md spells every property name correctly",
           vocabulary_violations(_text, f"{_id}/RULES.md"), [])

expect_reports(
    "fixture: the British spelling of the list property is reported",
    vocabulary_violations("write pyoneer_behaviours on the object", "fix"),
    "pyoneer_behaviours", "not one the engine reads")
expect_reports(
    "fixture: an invented property name is reported",
    vocabulary_violations("set pyoneer_gravity to 900", "fix"),
    "pyoneer_gravity", "not one the engine reads")
expect_reports(
    "fixture: a parameter override with a non-token key is reported",
    vocabulary_violations("set pyoneer_param_MoveSpeed", "fix"),
    "pyoneer_param_MoveSpeed", "not snake_case")
expect("fixture: a well-formed parameter override is clean",
       vocabulary_violations("set %smove_speed" % PARAM_PREFIX, "fix"), [])
expect("fixture: a layer capability the engine really reads is clean",
       vocabulary_violations("%s and %s" % (layer_profile.PASSABILITY,
                                            layer_profile.RENDERS), "fix"), [])


# ===========================================================================
print("\n7. both RULES.md files are honest about what exists")
# ===========================================================================
for _id, _text in RULES.items():
    expect_true(f"{_id}/RULES.md sends the reader to the generated document",
                "docs/BEHAVIORS.md" in _text)
    expect_true(f"{_id}/RULES.md names the regeneration command",
                REGENERATE in _text)
    expect(f"{_id}/RULES.md claims a behavior exists only when one does",
           EMPTY_MARKER in _text, not BEHAVIOR_REGISTRY)
    expect(f"{_id}/RULES.md names no Game* class the tree does not define",
           missing_class_names(_text, DEFINED), [])
    expect(f"{_id}/RULES.md names every behavior that claims {_id}",
           rules_coverage_violations(_text, _id, BEHAVIOR_REGISTRY), [])

expect_reports(
    "fixture: a genre-specific behavior missing from its rules is reported",
    rules_coverage_violations("nothing here", "platformer",
                              {"g": _spec("g", genres=("platformer",))}),
    "'g'", "'platformer'", "never names it")
expect("fixture: ...and naming it satisfies the rule",
       rules_coverage_violations("use `g` for this", "platformer",
                                 {"g": _spec("g", genres=("platformer",))}), [])
expect("fixture: a behavior for ANOTHER genre is not demanded here",
       rules_coverage_violations("nothing here", "topdown_rpg",
                                 {"g": _spec("g", genres=("platformer",))}), [])
expect("fixture: a bare mention without backticks does not count as naming it",
       len(rules_coverage_violations("use g for this", "platformer",
                                     {"g": _spec("g", genres=("platformer",))})),
       1)

expect("fixture: a rules file teaching an absent class is reported",
       missing_class_names("write a `GamePlatformerBody` that owns velocity.",
                           DEFINED),
       ["GamePlatformerBody"])
expect("fixture: a class the tree really defines is clean",
       missing_class_names("`GamePlayer` and `GameEntity` and `GameComponent`",
                           DEFINED), [])
expect_true("fixture: the naming placeholder is not mistaken for a class",
            not missing_class_names("name it `Game<Thing>Behavior`", DEFINED))


# ===========================================================================
print("\n8. the integration status in the file matches what the code does")
# ===========================================================================
_wired = entity_drives_behaviors()
expect("the file's WIRED banner appears only when the drive really runs",
       WIRED in DOC, _wired)
expect("...and the NOT WIRED banner only when it does not",
       UNWIRED in DOC, not _wired)
expect("exactly one of the two banners is present",
       (WIRED in DOC) + (UNWIRED in DOC), 1)
# The banner is derived from the same probe, so comparing the banner against
# the probe would be circular. The teeth are that the FILE ON DISK is compared
# against a LIVE probe: wire or un-wire the drive without regenerating and the
# pair above goes red.
#
# These three measure the drive itself rather than restating the banner. Each
# separates a distinct broken drive that a yes/no probe reports as working:
expect("no frames driven, no calls -- the drive does not fire at attach time",
       drive_calls(0), 0)
expect("three frames driven, three calls -- exactly one per frame",
       drive_calls(3), 3)
expect("...and a disabled behavior is skipped, not merely counted",
       drive_calls(3, enabled=False), 0)

_jump = "jump" in input_actions()[0]
expect("the file reports the jump binding as it actually is",
       "| a `jump` input action exists | **yes** |" in DOC
       or "| a `jump` input action exists | no |" in DOC, True)
expect("...and reports it correctly",
       "| a `jump` input action exists | %s |"
       % ("**yes**" if _jump else "no") in DOC, True)


# ===========================================================================
print("\n9. every integration row goes NO when the CODE is broken")
# ===========================================================================
# THE NEGATIVE CORPUS. `CLAUDE.md` routes every reader of this repository to
# docs/BEHAVIORS.md with the instruction to trust its measured integration
# table over any prose, including its own preamble -- so a detector that
# reports a wire which is not there is the most expensive kind of wrong
# available here. The sibling instrument next door was caught printing `yes`
# over broken code three passes running, and every one of those was found by a
# PERSON breaking the code by hand and watching the row not move.
#
# This section is that work written down. For every row: the mutations that
# MUST drive it to `no`, and at least one planted world that drives it to
# `yes`. A row whose corpus is one-sided fails the gate below, so an eighth
# row cannot land with a detector nobody has seen give both answers.
#
# NOTHING HERE EDITS A TRACKED FILE. The broken worlds are decoy source trees
# in memory, entity classes built in this file, an empty registry, a
# synthesised binding table, a planted input loader, and a `read_requests`
# swapped into `map_loader` for the length of one call.


def _row(rows, starts):
    """One row's verdict, addressed by the words the table prints."""
    for what, ok, _ in rows:
        if what.startswith(starts):
            return ok
    raise KeyError("no integration row starts %r -- a row was renamed, and "
                   "both the corpus and its coverage gate address rows by "
                   "the words they print" % starts)


def _cost(rows, starts):
    """One row's `what it takes` cell, addressed the same way."""
    for what, _, cost in rows:
        if what.startswith(starts):
            return cost
    raise KeyError(starts)


# -- rows 1 and 2: four shapes of entity -------------------------------------
class _NoHolder(_ProbeEntity):
    """An entity that reaches a frame with no holder at all.

    What `GameEntity.__init__` losing its one attribute looks like from out
    here, and the thing row 1 claims cannot happen.
    """

    def __init__(self):
        super().__init__()
        if hasattr(self, HOLDER):
            delattr(self, HOLDER)


class _ListHolder(_ProbeEntity):
    """`self.behaviors = []` -- the familiar spelling of the wrong type.

    A `hasattr` probe calls this wired. Nothing can be attached to it and
    nothing can be driven through it.
    """

    def __init__(self):
        super().__init__()
        setattr(self, HOLDER, [])


class _DeadDrive(_ProbeEntity):
    """`core_frame_update` left as the `pass` the row's own cost text names."""

    def core_frame_update(self, event=None):
        pass


class _DoubleDrive(_ProbeEntity):
    """A drive that runs every behavior TWICE per frame.

    Exactly double speed for a movement behavior, and indistinguishable from
    a working drive under a single-frame yes/no probe.
    """

    def core_frame_update(self, event=None):
        super().core_frame_update(event)
        super().core_frame_update(event)


# -- rows 4 and 5: shapes of a production module -----------------------------
_READER = ("from scripts.game.behavior import build, read_requests\n"
           "def compose(entity, obj):\n"
           "    entity.behaviors.attach_all(build(read_requests("
           "obj.properties)))\n")
_MODULE_SPELLING = ("from scripts.game import behavior\n"
                    "def compose(entity, obj):\n"
                    "    requests = behavior.read_requests(obj.properties)\n"
                    "    entity.behaviors.attach_all(behavior.build(requests))\n")
_DOTTED_SPELLING = ("import scripts.game.behavior\n"
                    "def compose(entity, obj):\n"
                    "    requests = scripts.game.behavior.read_requests("
                    "obj.properties)\n"
                    "    entity.behaviors.attach_all(requests)\n")
_SUBMODULE_SPELLING = ("from scripts.game.behavior.registry import "
                       "read_requests\n"
                       "def compose(entity, obj):\n"
                       "    entity.behaviors.attach_all(read_requests("
                       "obj.properties))\n")
_OWN_READ = ("from scripts.game.behavior import build\n"
             "class Loader:\n"
             "    def read_requests(self, properties):\n"
             "        return ()\n"
             "    def compose(self, entity, obj):\n"
             "        entity.behaviors.attach_all(\n"
             "            build(self.read_requests(obj.properties)))\n")
_IMPORT_ONLY = ("from scripts.game.behavior import read_requests\n"
                "def compose(entity, obj):\n"
                "    entity.behaviors.attach_all([])\n")
_NAME_ONLY = ("def compose(entity, obj):\n"
              "    entity.behaviors.attach_all(read_requests(obj.properties))\n")
_IN_COMMENT = ("from scripts.game.behavior import read_requests\n"
               "def compose(entity, obj):\n"
               "    # one day, read_requests(obj.properties) goes here\n"
               "    entity.behaviors.attach_all([])\n")
_IN_DOCSTRING = ('from scripts.game.behavior import read_requests\n'
                 'def compose(entity, obj):\n'
                 '    """Calls read_requests(obj.properties), then attaches."""\n'
                 '    entity.behaviors.attach_all([])\n')
_READ_NO_ATTACH = ("from scripts.game.behavior import read_requests\n"
                   "def compose(entity, obj):\n"
                   "    return read_requests(obj.properties)\n")
_ATTACH_ONLY = ("def compose(entity, requests):\n"
                "    entity.behaviors.attach_all(requests)\n")
_OWN_ATTACH = ("from scripts.game.behavior import read_requests\n"
               "class Layer:\n"
               "    def attach_all(self, items):\n"
               "        pass\n"
               "    def compose(self, obj):\n"
               "        self.attach_all(read_requests(obj.properties))\n")

# -- row 6: shapes of a gate -------------------------------------------------
_GATE = ("class Renderer:\n"
         "    def bind(self, tmx):\n"
         "        self.collision_field = field_from_map(tmx)\n"
         "    def gate(self, entity):\n"
         "        entity.collision_field = self.collision_field\n")
_SELF_ONLY = ("class Renderer:\n"
              "    def bind(self, tmx):\n"
              "        self.collision_field = field_from_map(tmx)\n"
              "    def gate(self, entity):\n"
              "        pass\n")
_GATE_NESTED = ("class Renderer:\n"
                "    def gate(self, record):\n"
                "        record.entity.collision_field = self.collision_field\n")
_GATE_COMMENT = ("class Renderer:\n"
                 "    def gate(self, entity):\n"
                 "        # entity.collision_field = self.collision_field\n"
                 "        return None\n")
_GATE_DOCSTRING = ('class Renderer:\n'
                   '    def gate(self, entity):\n'
                   '        """One day: entity.collision_field = self.field."""\n'
                   '        return None\n')
_GATE_COMPARED = ("class Renderer:\n"
                  "    def gate(self, entity):\n"
                  "        return entity.collision_field == self.collision_field\n")
_GATE_ANNOTATED = ("class Body:\n"
                   "    def __init__(self):\n"
                   "        self.collision_field: object | None = None\n")

# -- row 7: shapes of a binding table and of a loader ------------------------
_JUMPS = {"jump": ["keyboard:space"], "left": ["keyboard:a"]}
_NO_JUMP = {"left": ["keyboard:a"]}
_UNKNOWN_KEY = {"jump": ["keyboard:spacebar"], "left": ["keyboard:a"]}
_NO_BINDINGS: dict = {}


class _DroppingManager(InputActionManager):
    """A loader that builds every verb the table declares EXCEPT `jump`.

    The mutation the row exists for, and the one it could not see while it
    parsed the JSON: the file declares the verb, the manager does not hold it,
    and `held("jump")` is an unguarded dict index that raises inside
    `core_frame_update`.
    """

    def prepare_inputs(self, rebind=None):
        super().prepare_inputs(rebind)
        self.actions.pop("jump", None)
        return self


def _blind_reader(*_args, **_kwargs):
    """A spawn read that returns nothing, whatever the object declared."""
    return ()


def _fixed_reader(*_args, **_kwargs):
    """A spawn path that composes a list of its OWN, ignoring the object.

    The shape no call scan can see: `read_requests` is called, a record comes
    back FULL, and the token on it is not the token the author wrote. The spec
    is this file's own unregistered probe rather than a second live token, so
    the case still bites on a tree that registers exactly one behavior.
    """
    return (BehaviorRequest(spec=_SPY_SPEC, values={}, where="planted"),)


ROW_KEYS = ("`GameEntity.%s` exists" % HOLDER,
            "`GameEntity.core_frame_update` runs the drive",
            "a behavior is registered",
            "a declaration is turned into attached behaviors",
            "a **tmx object's**",
            "`GameEntity.%s` is assigned" % COLLISION_FIELD,
            "a `jump` input action exists")

CORPUS = [
    # -- row 1: the holder --------------------------------------------------
    (ROW_KEYS[0], True, {}, "the real `GameEntity`, constructed"),
    (ROW_KEYS[0], False, {"entity_class": _NoHolder},
     "the one attribute gone from `GameEntity.__init__`"),
    (ROW_KEYS[0], False, {"entity_class": _ListHolder},
     "`self.behaviors = []` -- the right name, the wrong type, and a "
     "`hasattr` probe would have called it wired"),

    # -- row 2: the drive ---------------------------------------------------
    (ROW_KEYS[1], True, {}, "the real drive"),
    (ROW_KEYS[1], False, {"entity_class": _DeadDrive},
     "`core_frame_update` back to the `pass` its own cost text names"),
    (ROW_KEYS[1], False, {"entity_class": _DoubleDrive},
     "a drive that runs every behavior TWICE per frame -- double speed, and "
     "a single-frame probe reports it as working"),
    (ROW_KEYS[1], False, {"entity_class": _NoHolder},
     "no holder at all: nothing to drive is not a drive that runs"),

    # -- row 3: the registry ------------------------------------------------
    (ROW_KEYS[2], True, {"registry": {"probe": _spec("probe")}},
     "one behavior registered"),
    (ROW_KEYS[2], False, {"registry": {}},
     "`register` never writes the table"),

    # -- row 4: a declaration read AND attached -----------------------------
    (ROW_KEYS[3], True, {"sources": {"scripts/core/compose.py": _READER}},
     "a production module that imports the read, calls it, and attaches"),
    (ROW_KEYS[3], True,
     {"sources": {"scripts/core/compose.py": _MODULE_SPELLING}},
     "...the module-attribute spelling counts too"),
    (ROW_KEYS[3], True,
     {"sources": {"scripts/core/compose.py": _DOTTED_SPELLING}},
     "...and so does `import scripts.game.behavior` spelled out in full"),
    (ROW_KEYS[3], True,
     {"sources": {"scripts/core/compose.py": _SUBMODULE_SPELLING}},
     "...and the import from the module that DEFINES it, not the package"),
    (ROW_KEYS[3], False, {"sources": {"scripts/core/compose.py": _OWN_READ}},
     "THE NAMED DEFECT: a module with its own `read_requests` METHOD, "
     "reached through no import -- which the bare `func.attr` match this "
     "replaces counted as the whole wire"),
    (ROW_KEYS[3], False, {"sources": {"scripts/core/compose.py": _IMPORT_ONLY}},
     "the import kept, every use of it deleted"),
    (ROW_KEYS[3], False, {"sources": {"scripts/core/compose.py": _NAME_ONLY}},
     "the import deleted, the call left standing"),
    (ROW_KEYS[3], False, {"sources": {"scripts/core/compose.py": _IN_COMMENT}},
     "the only call lives in a COMMENT"),
    (ROW_KEYS[3], False, {"sources": {"scripts/core/compose.py": _IN_DOCSTRING}},
     "...or in a DOCSTRING, which is where three of this package's real "
     "mentions live"),
    (ROW_KEYS[3], False,
     {"sources": {"scripts/core/compose.py": _READ_NO_ATTACH}},
     "THE MISSING HALF: every list is read and NOTHING attaches one"),
    (ROW_KEYS[3], False, {"sources": {"scripts/core/compose.py": _ATTACH_ONLY}},
     "...and the mirror: something attaches, nothing reads a declaration"),
    (ROW_KEYS[3], False, {"sources": {"scripts/core/compose.py": _OWN_ATTACH}},
     "the read is real and the attach is the module's OWN `attach_all` "
     "method, which is not the drive's holder"),
    (ROW_KEYS[3], False,
     {"sources": {"scripts/game/behavior/registry.py": _READER}},
     "the only reader is inside the package that DEFINES the read"),
    (ROW_KEYS[3], False, {"sources": {"tools/check_planted.py": _READER}},
     "the whole wire lives in a CHECK, which is not production"),

    # -- row 5: a tmx object's own property ---------------------------------
    (ROW_KEYS[4], True,
     {"sources": {"scripts/loaders/map_loader.py": _READER}},
     "a loader that reads the declaration, and a real spawn that carries the "
     "authored token onto the record"),
    (ROW_KEYS[4], False, {"reader": _blind_reader},
     "THE DRIVE: `read_requests` returns nothing, so the object's authored "
     "list reaches no record -- the scan beside it still says yes"),
    (ROW_KEYS[4], False, {"reader": _fixed_reader},
     "...and the quieter one: the spawn path composes a FIXED list of its "
     "own and never looks at the object, which no call scan can see"),
    (ROW_KEYS[4], False,
     {"sources": {"scripts/game/entity/player.py": _READER}},
     "the reader moved out of the spawn layer: `scripts/game/` is not "
     "`scripts/loaders/` or `scripts/core/`"),
    (ROW_KEYS[4], False,
     {"sources": {"scripts/loaders/map_loader.py": _OWN_READ}},
     "the loader's own same-named method, reached through no import"),

    # -- row 6: the collision gate ------------------------------------------
    (ROW_KEYS[5], True, {"sources": {"scripts/core/renderer.py": _GATE}},
     "the renderer hands its baked field to an entity"),
    (ROW_KEYS[5], True, {"sources": {"scripts/core/renderer.py": _GATE_NESTED}},
     "...and it counts when the entity is reached through a record"),
    (ROW_KEYS[5], False, {"sources": {"scripts/core/renderer.py": _SELF_ONLY}},
     "THE MUTATION THE REGEX SURVIVED: the hand-out deleted, the renderer's "
     "OWN `self.collision_field` left standing -- every body ungated, and "
     "the row said yes"),
    (ROW_KEYS[5], False,
     {"sources": {"scripts/core/renderer.py": _GATE_COMMENT}},
     "the assignment lives in a COMMENT, which the regex counted"),
    (ROW_KEYS[5], False,
     {"sources": {"scripts/core/renderer.py": _GATE_DOCSTRING}},
     "...or in a DOCSTRING, which it counted too"),
    (ROW_KEYS[5], False,
     {"sources": {"scripts/core/renderer.py": _GATE_COMPARED}},
     "...or is not an assignment at all: `== ` satisfied the regex's `=`"),
    (ROW_KEYS[5], False,
     {"sources": {"scripts/game/entity/body.py": _GATE_ANNOTATED}},
     "the annotated declaration does not count itself as its own consumer"),
    (ROW_KEYS[5], False, {"sources": {"tools/check_planted.py": _GATE}},
     "the only gate is in a CHECK, which is not production"),

    # -- row 7: the input verb ----------------------------------------------
    (ROW_KEYS[6], True, {"config": _JUMPS},
     "a table declaring `jump`, LOADED through `prepare_inputs`"),
    (ROW_KEYS[6], False, {"config": _NO_JUMP},
     "no `jump` declared: an authoring gap"),
    (ROW_KEYS[6], False, {"config": _NO_BINDINGS},
     "no binding at all"),
    (ROW_KEYS[6], False, {"config": _UNKNOWN_KEY},
     "`jump` bound to a key that does not exist: `validate_bindings` refuses "
     "the whole table, so no verb is pollable"),
    (ROW_KEYS[6], False, {"config": _JUMPS, "manager": _DroppingManager},
     "THE LOADER DROPS IT while the file still declares it -- the shape that "
     "printed **yes** for as long as this row read the JSON"),
]

# The gate that makes the corpus a rule rather than a habit. Both halves: the
# keys claim every row exactly once -- a renamed or an added row shows up here
# as UNCLAIMED rather than as a silent hole -- and each key carries a case
# that drives its row both ways.
_LIVE = [what for what, _, _ in integration_rows()]
expect("every integration row is claimed by exactly one corpus key",
       sorted(next((k for k in ROW_KEYS if w.startswith(k)),
                   "UNCLAIMED: " + w) for w in _LIVE),
       sorted(ROW_KEYS))
for _n, _key in enumerate(ROW_KEYS, 1):
    expect("row %d has a corpus case driving it BOTH ways" % _n,
           sorted({want for key, want, _, _ in CORPUS if key == _key}),
           [False, True])

for _key, _want, _kw, _label in CORPUS:
    expect("row %d %s <- %s" % (ROW_KEYS.index(_key) + 1,
                                "yes" if _want else "NO ", _label),
           _row(integration_rows(**_kw), _key), _want)

# The `no` cells are diagnostics, not just verdicts, and two of them have to
# tell apart failures a reader would otherwise act on identically.
expect_true("row 4's NO names the half that is missing, not just the row",
            "NOTHING in production calls" in
            _cost(integration_rows(
                sources={"scripts/core/compose.py": _READ_NO_ATTACH}),
                ROW_KEYS[3]))
expect_true("row 7 tells an authoring gap from a broken loader",
            "engine defect" in
            _cost(integration_rows(config=_JUMPS, manager=_DroppingManager),
                  ROW_KEYS[6]))
expect_true("...and says the opposite thing when nobody declared the verb",
            "one entry in `config/inputs.json`" in
            _cost(integration_rows(config=_NO_JUMP), ROW_KEYS[6]))

_TMP.cleanup()


# ===========================================================================
print("\n10. summary")
# ===========================================================================
print(f"\nassertions             : {len(asserted)}")
print(f"registry at HEAD       : {len(BEHAVIOR_REGISTRY)} behavior(s)")
print(f"genre packs            : {len(PACKS)}")
print(f"BEHAVIORS.md           : {len(DOC.splitlines())} lines")
print(f"drive wired            : {_wired}")
_dupes = sorted({label for label in asserted if asserted.count(label) > 1})
if _dupes:
    print(f"  FAIL duplicate assertion labels: {_dupes}")
    failures.extend(_dupes)

if failures:
    print(f"\nFAILED ({len(failures)}):")
    for item in failures:
        print(f"  - {item}")
    print(f"\nIf a BehaviorSpec or a genre pack changed, regenerate first:\n"
          f"    {REGENERATE}")
    raise SystemExit(1)
print("\nALL BEHAVIOR DOC CHECKS PASS")
