"""Verify the documentation SPINE, and generate the parts that can be generated.

    .venv/Scripts/python.exe tools/check_docs.py
    .venv/Scripts/python.exe tools/check_docs.py --write   # regenerate L1 docs

`tools/check_behavior_docs.py` proves one generated document agrees with one
subsystem. This file proves the whole tree of documents agrees with the tree of
code, and that a reader arriving cold can be routed by it.

WHY A DOCS CHECK IS NOT CEREMONY
--------------------------------
Every defect this file guards has already been paid for here. `README.md` still
states three shipped subsystems as missing. `docs/BEHAVIORS.md` -- the repo's
GENERATED document -- ships an example naming a behavior token that does not
exist, which makes a map raise at load, because its preamble is hand-written
prose living inside the generator: generation guarantees the file matches the
generator, never that the generator matches the code. Nine documentation sites
stated the opposite of a shipped wire in one review pass, because nine sites
existed. A document that lies costs more than one that is missing: a missing
document sends a reader to the source, a lying one sends them to write a `.tmx`
that raises.

WHAT IS ASSERTED
----------------
     1. every document declares its LAYER, and every layer's obligations are met
     2. NAVIGATION, both halves: every path CLAUDE.md names exists, AND every
        document under docs/ is named by CLAUDE.md (no unreachable document)
     3. the ROSTER, both halves: every roster entry has a file on disk, AND
        every check file on disk is in the roster -- plus every `check_*` a live
        document names is a real roster entry
     4. every `path.py:LINE` a live document quotes points at a file that is
        still that long
     5. the ANCHOR table in CLAUDE.md: each numbered line still contains the
        quoted text  <- the strongest single assertion here
     6. FACT AGREEMENT: every fact a live document states that the CODE also
        knows is compared against the code -- token lists, roster counts, verb
        counts, spawnable types, input verbs, the property vocabulary
     7. the L1 documents are byte-for-byte what this file's generators produce
     8. ONE HOME: a roster blurb appears only in docs/CHECKS.md
     9. known-stale text in a FOREIGN generated document is pinned, and the pin
        fails when the defect is fixed as loudly as when a new one appears

THE ANTI-DRIFT POSITION THIS FILE TAKES
---------------------------------------
"No two documents may state the same fact" is unenforceable and also wrong --
routing requires some repetition. What is enforceable is stronger: **every
restatement of a fact the code knows is checked against the code**. So
CLAUDE.md may list the behavior tokens, and docs/PLACEABLE.md may list the
spawnable types, and neither can drift, because rule 6 recomputes both from the
registries on every run. Repetition is legal exactly where it is measured.

NO MAP CONTENT IS PINNED
------------------------
`data/maps/test.tmx` is never read. Every fact below comes from a registry, a
config file, the check roster, or a source line the docs themselves nominate.
"""
from __future__ import annotations

import _bootstrap  # noqa: F401  (must precede engine imports)

import argparse
import ast
import json
import os
import re
import sys

ROOT = _bootstrap.REPO_ROOT
DOCS = os.path.join(ROOT, "docs")

failures: list[str] = []
checked = 0


def expect(label: str, got, want) -> None:
    global checked
    checked += 1
    if got == want:
        print(f"    ok    {label}")
    else:
        print(f"    FAIL  {label}\n            got : {got!r}\n            want: {want!r}")
        failures.append(label)


def expect_empty(label: str, offenders) -> None:
    offenders = list(offenders)
    expect(label, offenders[:12], [])


def read(relpath: str) -> str:
    with open(os.path.join(ROOT, relpath.replace("/", os.sep)),
              encoding="utf-8", newline="") as handle:
        return handle.read().replace("\r\n", "\n")


def lines_of(relpath: str) -> list[str]:
    return read(relpath).split("\n")


# ---------------------------------------------------------------------------
# The document layers
# ---------------------------------------------------------------------------
# L0  the boot document. Exactly one.
# L1  generated by THIS file. Must equal the generator byte for byte.
# L2  hand-written, live, question-scoped. Fact-checked; needs a stamp.
# L3  dated archive. EXEMPT from fact checks, and must say so in a banner --
#     the exemption is opt-in and visible, which is the only kind that keeps a
#     stale number from quietly becoming a live claim.

MARKER = re.compile(r"<!--\s*pyoneer-doc:\s*(L[0-3])\s*-->")
STAMP = re.compile(r"<!--\s*pyoneer-stamp:\s*(.+?)\s*-->", re.S)
ARCHIVE_BANNER = "pyoneer-archive"

BOOT = "CLAUDE.md"

# Generated somewhere ELSE. This file does not regenerate them and must not
# assert they equal ITS generators -- but they are live, so they are still
# fact-checked and still routed.
FOREIGN_GENERATED = {
    "docs/BEHAVIORS.md": "tools/check_behavior_docs.py --write",
}

# Text that is KNOWN WRONG in a document this pass may not edit, pinned so it
# cannot get worse and cannot be forgotten. Each entry fails in BOTH
# directions: if the text disappears the pin is stale and must be deleted in
# the same change that fixed the defect; if new bad text appears it is not
# pinned and rule 6 catches it.
PINNED_STALE = [
    ("docs/BEHAVIORS.md", "topdown_move,tile_collision",
     "`tile_collision` is not a registered token and makes a map raise at "
     "load. It lives in the generator's hand-written preamble: "
     "scripts/game/behavior/registry.py:366, and is repeated at "
     "scripts/game/behavior/base.py:102 and registry.py:145."),
]


def classify() -> dict[str, str]:
    """relpath -> layer, for CLAUDE.md and every markdown file under docs/."""
    out = {BOOT: "L0"}
    for name in sorted(os.listdir(DOCS)):
        if not name.endswith(".md"):
            continue
        rel = "docs/" + name
        if rel in FOREIGN_GENERATED:
            out[rel] = "L1"
            continue
        found = MARKER.search(read(rel))
        out[rel] = found.group(1) if found else "?"
    return out


# ---------------------------------------------------------------------------
# The facts, read from the code -- never from a document
# ---------------------------------------------------------------------------

def roster() -> list[tuple[str, str]]:
    """The CHECKS list out of tools/check_all.py, parsed, not imported.

    Parsed rather than imported because importing it RUNS the whole suite.
    """
    tree = ast.parse(read("tools/check_all.py"))
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and getattr(node.targets[0], "id", "") == "CHECKS":
            return [tuple(pair) for pair in ast.literal_eval(node.value)]
    raise AssertionError("tools/check_all.py has no CHECKS list")


ROSTER = roster()
ROSTER_NAMES = [name for name, _ in ROSTER]
ROSTER_BLURBS = {blurb: name for name, blurb in ROSTER}

from scripts.core.depth import (  # noqa: E402
    LAYER_NAME_ALIASES, MAP_DEPTH, OBJECT_CONVERTER, OBJECT_DEPTH)
from scripts.core.layer_profile import PREFIX  # noqa: E402
from scripts.core.spawn import SPAWN_REGISTRY  # noqa: E402
from scripts.game.behavior.base import ACTOR, BEHAVIORS, PARAM_PREFIX  # noqa: E402
from scripts.game.behavior.registry import BEHAVIOR_REGISTRY  # noqa: E402

with open(os.path.join(ROOT, "config", "inputs.json"), encoding="utf-8") as _h:
    INPUT_VERBS: dict = json.load(_h)

TOKENS = sorted(BEHAVIOR_REGISTRY)

try:
    import editor.core.verbs  # noqa: F401,E402  (populates the registry)
    from editor.core.commands import describe_all, verb_names  # noqa: E402
    EDITOR_VERBS = verb_names()
except Exception as _exc:                                   # pragma: no cover
    describe_all = None
    EDITOR_VERBS = None
    print(f"    note  editor verbs unavailable ({type(_exc).__name__}); "
          f"docs/COMMANDS.md will not be verified this run")


# ---------------------------------------------------------------------------
# The generators
# ---------------------------------------------------------------------------

GEN_BANNER = (
    "<!-- pyoneer-doc: L1 -->\n"
    "<!-- GENERATED by tools/check_docs.py. Do not edit. "
    "Regenerate: .venv/Scripts/python.exe tools/check_docs.py --write -->\n"
)


def _class_exists(name: str) -> bool:
    """Is `class <name>` defined anywhere under scripts/?"""
    needle = "class " + name
    for base, _dirs, files in os.walk(os.path.join(ROOT, "scripts")):
        for file in files:
            if not file.endswith(".py"):
                continue
            with open(os.path.join(base, file), encoding="utf-8",
                      errors="replace") as handle:
                for line in handle:
                    if line.startswith(needle) and line[len(needle)] in "(:":
                        return True
    return False


def render_placeable() -> str:
    from scripts.core.spawn import resolve_depth

    out = [GEN_BANNER, "# Placeable — what a map may legally contain", "",
           "Generated from `SPAWN_REGISTRY`, `scripts/core/depth.py` and",
           "`config/inputs.json`. This document answers *authoring* questions;",
           "for what a behavior DOES see [`BEHAVIORS.md`](BEHAVIORS.md), and for",
           "why something is inert see [`DIAGNOSE.md`](DIAGNOSE.md).", ""]

    out += ["## Object `type` values that spawn", "",
            "The `Type` field on a tmx object. An object whose type is not in",
            "this table makes the **whole map raise at load** — deliberately,",
            "because a skipped object looks like a working one.", "",
            "| `type` | default depth | spawned as |", "|---|---|---|"]
    for name in sorted(SPAWN_REGISTRY):
        factory = SPAWN_REGISTRY[name]
        try:
            depth = resolve_depth(name)
        except Exception:                                    # pragma: no cover
            depth = "—"
        out.append(f"| `{name}` | {depth} | `{getattr(factory, '__name__', factory)}` |")
    out.append("")

    phantom = [n for n in sorted(OBJECT_CONVERTER) if n not in SPAWN_REGISTRY]
    out += ["## Names that look placeable and are not", "",
            "`scripts/core/depth.py`'s `OBJECT_CONVERTER` maps these to a depth,",
            "which reads as a list of placeable classes. It is not one — a depth",
            "mapping is not a registration. Measured against the tree:", "",
            "| name in `OBJECT_CONVERTER` | `class` exists in `scripts/`? | spawnable? |",
            "|---|---|---|"]
    for name in phantom:
        out.append(f"| `{name}` | {'yes' if _class_exists(name) else '**no**'} | no |")
    out += ["", f"{len(phantom)} of {len(OBJECT_CONVERTER)} entries are not "
                "spawnable. Put one in a `Type` field and the map raises.", ""]

    out += ["## Tile layer names that resolve to a depth", "",
            "A tile layer whose name is not here is **silently not drawn** —",
            "`resolve_layer_depth` returns `None` and nothing warns.", "",
            "| layer name | depth |", "|---|---|"]
    for name, depth in sorted(MAP_DEPTH.items(), key=lambda kv: (kv[1], kv[0])):
        out.append(f"| `{name}` | {depth} |")
    out.append("")
    if LAYER_NAME_ALIASES:
        out += ["Aliases, which resolve to the canonical name above:", "",
                "| authored spelling | resolves to |", "|---|---|"]
        for bad, good in sorted(LAYER_NAME_ALIASES.items()):
            out.append(f"| `{bad}` | `{good}` |")
        out.append("")

    out += ["## Object group depth names", "",
            "| name | depth |", "|---|---|"]
    for name, depth in sorted(OBJECT_DEPTH.items(), key=lambda kv: (kv[1], kv[0])):
        out.append(f"| `{name}` | {depth} |")
    out.append("")

    out += ["## The tmx property vocabulary", "",
            "| property | meaning |", "|---|---|",
            f"| `{BEHAVIORS}` | comma-separated behavior tokens, on the OBJECT |",
            f"| `{PARAM_PREFIX}<key>` | one behavior parameter |",
            f"| `{ACTOR}` | actors-table row id (no engine reader yet) |",
            "",
            f"Every custom property starts `{PREFIX}`. The prefix is not style:",
            "pytmx raises and makes the whole map unloadable if a property",
            "shadows one of its own attribute names.", "",
            "Registered behavior tokens (see [`BEHAVIORS.md`](BEHAVIORS.md) for",
            "what each one does and whether it is wired):", "",
            "    " + " ".join(TOKENS), ""]

    out += ["## Input verbs", "",
            "Bound in `config/inputs.json`. A behavior polling a verb that is",
            "not here raises at attach — add the binding in the same change.", "",
            "| verb | bindings |", "|---|---|"]
    for verb in sorted(INPUT_VERBS):
        out.append(f"| `{verb}` | " + ", ".join(f"`{b}`" for b in INPUT_VERBS[verb]) + " |")
    out.append("")
    return "\n".join(out)


def render_checks() -> str:
    out = [GEN_BANNER, "# Checks — the roster, generated from it", "",
           "Generated from `tools/check_all.py`'s `CHECKS` list and each",
           "module's own first docstring line. Run the suite:", "",
           "    .venv/Scripts/python.exe tools/check_all.py", "",
           "One check on its own:", "",
           "    .venv/Scripts/python.exe tools/check_<name>.py", "",
           "A new check goes into the roster **in the same change** — three",
           "have been written, passed, and never run by the suite. A check that",
           "did not run has proved nothing, which is why an absent optional",
           "dependency reports `SKIP` and never `PASS`.", "",
           f"{len(ROSTER)} checks:", "",
           "| check | roster line | module says |", "|---|---|---|"]
    for name, blurb in ROSTER:
        rel = f"tools/check_{name}.py"
        first = ""
        try:
            first = lines_of(rel)[0].lstrip('"').strip()
        except OSError:                                      # pragma: no cover
            first = "**FILE MISSING**"
        out.append(f"| `{name}` | {blurb} | {first} |")
    out += ["", "`tools/smoke.py` runs after the roster and is not a check: it",
            "reports a frame hash, the component census, the blit-token",
            "histogram by depth, culled draws and listener invocations. It",
            "injects **no input**, so a clean smoke never means nothing",
            "changed.", ""]
    return "\n".join(out)


def render_commands() -> str:
    assert describe_all is not None
    body = describe_all(title="Command vocabulary")
    return GEN_BANNER + body if body.startswith("# ") else GEN_BANNER + body


GENERATED = {
    "docs/PLACEABLE.md": render_placeable,
    "docs/CHECKS.md": render_checks,
}
if describe_all is not None:
    GENERATED["docs/COMMANDS.md"] = render_commands


def write_all() -> None:
    for rel, render in GENERATED.items():
        path = os.path.join(ROOT, rel.replace("/", os.sep))
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(render())
        print(f"  wrote {rel}")


parser = argparse.ArgumentParser()
parser.add_argument("--write", action="store_true",
                    help="regenerate the L1 documents and exit")
args = parser.parse_args()
if args.write:
    write_all()
    raise SystemExit(0)


print("Verifying the documentation spine\n")

LAYERS = classify()
BOOT_TEXT = read(BOOT)
LIVE = [rel for rel, layer in LAYERS.items() if layer in ("L0", "L1", "L2")]
ARCHIVE = [rel for rel, layer in LAYERS.items() if layer == "L3"]


# ---------------------------------------------------------------------------
print("1. every document declares its layer, and meets that layer's obligations")
# ---------------------------------------------------------------------------
expect_empty("every docs/*.md carries a `pyoneer-doc: L0..L3` marker",
             [rel for rel, layer in LAYERS.items() if layer == "?"])
expect("exactly one L0 boot document",
       sorted(r for r, v in LAYERS.items() if v == "L0"), [BOOT])
expect_empty("every L2 document carries a `pyoneer-stamp:`",
             [rel for rel, layer in LAYERS.items()
              if layer == "L2" and not STAMP.search(read(rel))])
expect_empty("every L3 archive says it is exempt (carries the archive banner)",
             [rel for rel in ARCHIVE if ARCHIVE_BANNER not in read(rel)])
expect_empty("no L1 document is hand-editable without a named generator",
             [rel for rel, layer in LAYERS.items()
              if layer == "L1" and rel not in GENERATED and rel not in FOREIGN_GENERATED])


# ---------------------------------------------------------------------------
print("\n2. navigation, both halves")
# ---------------------------------------------------------------------------
# Half one: every repo path the boot document names resolves.
PATH_RX = re.compile(r"[`(]((?:docs|tools|scripts|editor|config|demos|data)"
                     r"/[A-Za-z0-9_<>./-]*?\.(?:md|py|json|tmx))[`)]")
named = sorted({m.group(1) for m in PATH_RX.finditer(BOOT_TEXT)})


def resolves(rel: str) -> bool:
    if "<" in rel:                       # editor/genres/<id>/RULES.md
        import glob
        pattern = re.sub(r"<[^>]+>", "*", rel)
        return bool(glob.glob(os.path.join(ROOT, pattern.replace("/", os.sep))))
    return os.path.exists(os.path.join(ROOT, rel.replace("/", os.sep)))


expect_empty("every repo path CLAUDE.md names exists",
             [rel for rel in named if not resolves(rel)])
expect("CLAUDE.md names a non-trivial number of paths", len(named) >= 12, True)

# Half two: no document under docs/ is unreachable. "Mentioned somewhere in
# CLAUDE.md" is too weak -- a doc named only in a KNOWN GAPS bullet is not
# routed. The assertion is against the NAVIGATION TABLE itself.
nav = re.search(r"## The query playbook\n(.*?)\n## ", BOOT_TEXT, re.S)
expect("CLAUDE.md has a query playbook section", nav is not None, True)
NAV = "\n".join(l for l in (nav.group(1) if nav else "").split("\n")
                if l.startswith("|"))
expect_empty("every docs/*.md is routed by the navigation table",
             [rel for rel in LAYERS if rel != BOOT and rel not in NAV])
expect("the navigation table routes by question shape, not by file name "
       "(every row asks something in quotes)",
       all('"' in row for row in NAV.split("\n")[2:] if row.strip()), True)


# ---------------------------------------------------------------------------
print("\n3. the check roster, both halves")
# ---------------------------------------------------------------------------
on_disk = sorted(f[len("check_"):-len(".py")]
                 for f in os.listdir(os.path.join(ROOT, "tools"))
                 if f.startswith("check_") and f.endswith(".py") and f != "check_all.py")


def tracked_checks() -> list[str] | None:
    """Check modules git knows about, or None when git cannot answer.

    The roster law is "a new check joins the roster IN THE SAME CHANGE", and a
    change is a commit -- so the set this rule judges is the TRACKED one. An
    untracked `tools/check_*.py` is another agent's work in flight, not a
    violation, and failing on it would make this check report someone else's
    half-finished tree as this one's. It is reported below instead, so nothing
    hides. The moment such a file is committed without a roster line, this
    goes red.
    """
    import subprocess
    try:
        out = subprocess.run(["git", "ls-files", "tools/check_*.py"],
                             cwd=ROOT, capture_output=True, text=True, timeout=30)
    except Exception:                                        # pragma: no cover
        return None
    if out.returncode != 0:                                  # pragma: no cover
        return None
    return sorted(os.path.basename(p)[len("check_"):-len(".py")]
                  for p in out.stdout.split("\n")
                  if p.strip() and not p.endswith("check_all.py"))


TRACKED = tracked_checks()
judged = on_disk if TRACKED is None else TRACKED
expect_empty("every roster entry has a file on disk",
             [n for n in ROSTER_NAMES if n not in on_disk])
expect_empty("every TRACKED check file is in the roster",
             [n for n in judged if n not in ROSTER_NAMES])
in_flight = [n for n in on_disk if n not in ROSTER_NAMES and n not in judged]
if in_flight:
    print(f"    note  untracked and unrostered (in flight, not judged): "
          f"{', '.join('check_' + n for n in in_flight)}")
expect("no duplicate roster entries", len(set(ROSTER_NAMES)), len(ROSTER_NAMES))

CHECK_RX = re.compile(r"\bcheck_([a-z0-9_]+)\b")
unknown_named = []
for rel in LIVE:
    for name in sorted(set(CHECK_RX.findall(read(rel)))):
        if name not in ROSTER_NAMES and name not in ("all", "docs"):
            unknown_named.append(f"{rel}: check_{name}")
expect_empty("every check a LIVE document names is in the roster", unknown_named)


# ---------------------------------------------------------------------------
print("\n4. every file:line a live document quotes still reaches that far")
# ---------------------------------------------------------------------------
REF_RX = re.compile(r"\b([A-Za-z0-9_.-]+(?:/[A-Za-z0-9_.-]+)+\.(?:py|json|tmx|md)):(\d+)")
stale_refs = []
ref_count = 0
for rel in LIVE:
    for match in REF_RX.finditer(read(rel)):
        target, number = match.group(1), int(match.group(2))
        ref_count += 1
        path = os.path.join(ROOT, target.replace("/", os.sep))
        if not os.path.isfile(path):
            stale_refs.append(f"{rel} -> {target}:{number} (no such file)")
            continue
        if number > len(lines_of(target)):
            stale_refs.append(f"{rel} -> {target}:{number} "
                              f"(only {len(lines_of(target))} lines)")
expect_empty("no live document quotes a line past the end of its file", stale_refs)
expect("live documents quote at least a few source lines", ref_count >= 8, True)


# ---------------------------------------------------------------------------
print("\n5. the anchor table: every quoted line still says what it says")
# ---------------------------------------------------------------------------
block = re.search(r"```anchors\n(.*?)```", BOOT_TEXT, re.S)
expect("CLAUDE.md carries an ```anchors``` block", block is not None, True)
anchors: list[tuple[str, int, str]] = []
if block:
    for raw in block.group(1).strip().split("\n"):
        if not raw.strip():
            continue
        head, _, needle = raw.partition(" :: ")
        target, _, number = head.rpartition(":")
        anchors.append((target.strip(), int(number), needle))
expect("the anchor table is not empty enough to be decorative",
       len(anchors) >= 8, True)

broken = []
for target, number, needle in anchors:
    path = os.path.join(ROOT, target.replace("/", os.sep))
    if not os.path.isfile(path):
        broken.append(f"{target}:{number} -- no such file")
        continue
    body = lines_of(target)
    if number > len(body):
        broken.append(f"{target}:{number} -- file has {len(body)} lines")
        continue
    if needle not in body[number - 1]:
        elsewhere = [i + 1 for i, line in enumerate(body) if needle in line]
        broken.append(f"{target}:{number} no longer contains {needle!r}"
                      + (f" -- it moved to line {elsewhere[0]}" if elsewhere
                         else " -- and it is gone from the file entirely"))
expect_empty("every anchored line still contains its quoted text", broken)


# ---------------------------------------------------------------------------
print("\n6. fact agreement: what a live document claims vs what the code holds")
# ---------------------------------------------------------------------------
ESCAPE = "<!-- fact: historical"          # opt-in, must carry a reason

COUNT_RX = re.compile(r"(\d+)[^\S\n]*\**[^\S\n]*(checks?|verbs)\b")
wrong_counts = []
for rel in LIVE:
    for lineno, line in enumerate(lines_of(rel), 1):
        if ESCAPE in line:
            continue
        for match in COUNT_RX.finditer(line):
            value, kind = int(match.group(1)), match.group(2)
            if kind.startswith("check"):
                want = len(ROSTER)
            elif EDITOR_VERBS is None:
                continue
            else:
                want = len(EDITOR_VERBS)
            if value != want:
                wrong_counts.append(f"{rel}:{lineno} says {value} {kind}, "
                                    f"the tree holds {want}")
expect_empty("no live document states a stale roster or verb count", wrong_counts)

# Behavior tokens quoted in a `pyoneer_behaviors` value must all resolve. This
# is the token-VALUE twin of check_behavior_docs' property-NAME rule, which is
# blind to values -- and it is the rule that catches `tile_collision`.
# Matches both the tmx form  <property name="pyoneer_behaviors" value="a,b"/>
# and the prose form         pyoneer_behaviors="a,b"
VALUE_RX = re.compile(re.escape(BEHAVIORS) + r'"?\s*(?:value)?=\s*"([^"]*)"')
bad_tokens = []
for rel in LIVE:
    text = read(rel)
    for match in VALUE_RX.finditer(text):
        lineno = text.count("\n", 0, match.start()) + 1
        for token in [t.strip() for t in match.group(1).split(",") if t.strip()]:
            if token not in BEHAVIOR_REGISTRY:
                bad_tokens.append((rel, lineno, token))
pinned_hits = []
unpinned = []
for rel, lineno, token in bad_tokens:
    if any(rel == prel and token in pin for prel, pin, _ in PINNED_STALE):
        pinned_hits.append((rel, token))
    else:
        unpinned.append(f"{rel}:{lineno} declares behavior token {token!r}, "
                        f"which is not registered -- a map carrying it raises at load")
expect_empty("every behavior token a live document declares is registered "
             "(unpinned)", unpinned)

# L0 may NAME a token, and may not ENUMERATE the registry: a table that is
# generated elsewhere must not be copied into the boot document, or the boot
# document becomes the thing that rots. Both halves -- every token it names
# must resolve, and it must name strictly fewer than all of them.
boot_tokens = sorted(t for t in TOKENS
                     if re.search(rf"(?<![a-z_]){re.escape(t)}(?![a-z_])", BOOT_TEXT))
expect("CLAUDE.md does not enumerate the registry (that is BEHAVIORS.md's job)",
       len(boot_tokens) < len(TOKENS) and len(boot_tokens) >= 1, True)
expect("CLAUDE.md lists exactly the bound input verbs",
       sorted(v for v in INPUT_VERBS
              if re.search(rf"(?<![a-z_]){re.escape(v)}(?![a-z_])", BOOT_TEXT)),
       sorted(INPUT_VERBS))
expect("CLAUDE.md names the spawnable types and no others",
       sorted(n for n in set(SPAWN_REGISTRY) | set(OBJECT_CONVERTER)
              if f"**`{n}`**" in BOOT_TEXT),
       sorted(SPAWN_REGISTRY))
expect_empty("CLAUDE.md spells the property vocabulary the way the code does",
             [name for name in (PREFIX, BEHAVIORS, PARAM_PREFIX, ACTOR)
              if name not in BOOT_TEXT])
# Catches `GameFoo`, `GameFoo.method`, `GameFoo(` -- the phantom-class trap in
# scripts/core/depth.py is four names that read as placeable and exist nowhere.
CLASS_RX = re.compile(r"`(Game[A-Za-z]+)(?=[.`(\s])")
expect_empty("CLAUDE.md and DIAGNOSE.md name no absent Game* class",
             [f"{rel}: {name}" for rel in (BOOT, "docs/DIAGNOSE.md")
              for name in sorted(set(CLASS_RX.findall(read(rel))))
              if not _class_exists(name)])


# ---------------------------------------------------------------------------
print("\n7. the generated documents are exactly what the generators produce")
# ---------------------------------------------------------------------------
for rel, render in GENERATED.items():
    path = os.path.join(ROOT, rel.replace("/", os.sep))
    on_file = read(rel) if os.path.isfile(path) else "<<absent>>"
    want = render()
    expect(f"{rel} is byte-identical to its generator", on_file == want, True)
    if on_file != want:
        # Say WHICH line and say the command. A generated doc going stale is
        # the normal consequence of adding a check or a verb, and the fix is
        # one command -- an unexplained boolean here would read as a bug in
        # the doc rather than as "you changed the thing it is generated from".
        a, b = on_file.split("\n"), want.split("\n")
        for i in range(max(len(a), len(b))):
            if a[i:i + 1] != b[i:i + 1]:
                print(f"          first difference at line {i + 1}:")
                print(f"            on disk : {(a[i:i+1] or ['<eof>'])[0][:90]!r}")
                print(f"            should  : {(b[i:i+1] or ['<eof>'])[0][:90]!r}")
                break
        print("          fix: .venv/Scripts/python.exe tools/check_docs.py --write")
if describe_all is None:                                     # pragma: no cover
    print("    note  docs/COMMANDS.md not verified (editor not importable)")


# ---------------------------------------------------------------------------
print("\n8. one home: a roster blurb lives in docs/CHECKS.md and nowhere else")
# ---------------------------------------------------------------------------
copies = []
for rel in LIVE + ARCHIVE:
    if rel == "docs/CHECKS.md":
        continue
    text = read(rel)
    copies += [f"{rel}: {blurb!r}" for blurb in ROSTER_BLURBS if blurb in text]
expect_empty("no document restates a roster blurb", copies)


# ---------------------------------------------------------------------------
print("\n9. pinned known-stale text: still there, and nothing worse")
# ---------------------------------------------------------------------------
for rel, needle, why in PINNED_STALE:
    present = needle in read(rel)
    expect(f"pin still applies: {rel} contains {needle!r}", present, True)
    if present:
        print(f"          reason: {why}")
    else:
        failures.append(f"stale pin for {rel}")
        print(f"          the defect appears FIXED -- delete this pin in the "
              f"same change ({rel})")
expect("every pinned defect was actually observed",
       len(pinned_hits) >= 1 or not PINNED_STALE, True)


# ---------------------------------------------------------------------------
print()
print(f"documents        : {len(LAYERS)}  "
      f"(L0 1, L1 {sum(1 for v in LAYERS.values() if v == 'L1')}, "
      f"L2 {sum(1 for v in LAYERS.values() if v == 'L2')}, "
      f"L3 {len(ARCHIVE)})")
print(f"roster           : {len(ROSTER)} checks")
print(f"behavior tokens  : {len(TOKENS)}")
print(f"anchors verified : {len(anchors)}")
print(f"file:line refs   : {ref_count}")
print(f"assertions       : {checked}")
if failures:
    print(f"\nFAIL ({len(failures)}): " + "; ".join(failures[:8]))
    sys.exit(1)
print("\nALL DOC ASSERTIONS PASS")
