"""Verify the behavior system's DOCUMENTATION cannot drift from the system.

    .venv/Scripts/python.exe tools/check_behavior_docs.py
    .venv/Scripts/python.exe tools/check_behavior_docs.py --write   # regenerate

`tools/check_behavior.py` proves the machinery works. This file proves the
paper agrees with the machinery, which is a separate failure and a worse one:
a broken behavior raises on the first frame, while a document that describes a
behavior the engine cannot run sends an AI to write a `.tmx` that raises at
load, and a document that omits one the engine CAN run means the behavior is
never used at all.

WHAT IS ASSERTED
----------------
     1. `docs/BEHAVIORS.md` is exactly what the generator produces, and its
        first half is byte-for-byte `registry.describe_all()`
     2. the catalogue in the FILE names exactly the registered behaviors,
        in both of the two places it names them
     3. every parameter the file documents is one its behavior declares
     4. every actors column a behavior consumes is declared by the genre
        pack that behavior claims  <- the one with teeth
     5. a pack's `object_types` are all spawnable, so an authored object
        cannot make the map raise at load
     6. every `pyoneer_*` property name printed in the docs or in either
        RULES.md is a real vocabulary constant, correctly spelled
     7. both RULES.md files point at the generated document, do not claim a
        behavior exists while the registry is empty, and name no `Game*`
        class that is absent from the tree
     8. the integration status written in the file matches what the code
        actually does when driven

THE DOCUMENT IS GENERATED, INCLUDING THE PARTS THAT ARE NOT `describe_all`
-------------------------------------------------------------------------
`describe_all()` renders the registry. `render_doc()` below renders the
registry AND the two things the registry cannot see: what the surrounding
engine has actually wired up, and what each genre pack declares. Both halves
are derived -- the integration table is produced by DRIVING a real
`GameEntity`, not by reading a flag someone remembered to set -- so the whole
file is regenerated by one command and the check is an equality.

THE FIXTURES ARE THIS FILE'S OWN
--------------------------------
A rule run only over the live tree passes whenever the live tree happens to be
clean, and passes vacuously whenever it iterates nothing. So each rule below
is driven twice: once against a hand-built fixture registry and fixture genre
pack that is KNOWN to violate it, and once against the live registry and the
real packs, which must be clean. `data/maps/test.tmx` is never read.
"""
from __future__ import annotations

import _bootstrap  # noqa: F401  (must precede engine imports)

import argparse
import ast
import json
import os
import re
import sys

import pygame

pygame.init()

from editor.core import genre as genre_module
from editor.core.genre import (GenreField, GenreLayer, GenreObjectClass,
                               GenrePack, GenreTable)
from scripts.core import layer_profile
from scripts.core.event_manager import PyoneerEvent
from scripts.core.event_types import GameEventType
from scripts.core.spawn import SPAWN_REGISTRY
from scripts.game.behavior import (ACTOR, BEHAVIOR_REGISTRY, BEHAVIORS,
                                   PARAM_PREFIX, TOKEN, BehaviorParam,
                                   BehaviorSpec, EntityBehavior,
                                   EntityBehaviors, describe_all, format_list,
                                   parse_list, validate_list)
from scripts.game.entity.game_entity import GameEntity

ROOT = _bootstrap.REPO_ROOT
DOC_PATH = os.path.join(ROOT, "docs", "BEHAVIORS.md")
INPUTS_PATH = os.path.join(ROOT, "config", "inputs.json")
GENRES_DIR = genre_module.GENRES_DIR

REGENERATE = ".venv/Scripts/python.exe tools/check_behavior_docs.py --write"

SENTINEL = ("<!-- Everything above this line is `describe_all()` in "
            "scripts/game/behavior/registry.py. Everything below is derived "
            "from the engine and the genre packs by tools/check_behavior_docs.py. "
            "Regenerate the whole file with:  %s  -->" % REGENERATE)

WIRED = "**Integration status: the per-frame drive is WIRED.**"
UNWIRED = "**Integration status: the per-frame drive is NOT WIRED.**"
EMPTY_MARKER = "**No behavior is registered yet.**"

failures: list[str] = []
asserted: list[str] = []


def expect(label, got, want):
    asserted.append(label)
    ok = got == want
    print(f"  {'ok  ' if ok else 'FAIL'} {label:<62} got={got!r} want={want!r}")
    if not ok:
        failures.append(label)


def expect_true(label, got):
    asserted.append(label)
    ok = bool(got)
    print(f"  {'ok  ' if ok else 'FAIL'} {label:<62} got={got!r}")
    if not ok:
        failures.append(label)


def expect_reports(label, violations, *fragments):
    """Exactly one violation, and it must name every fragment.

    The fragments are the teeth. `len(violations) == 1` passes for a
    violation raised by the wrong rule about the wrong thing, and this check
    exists precisely to distinguish "the column is missing" from "the pack is
    missing" -- two rules that share a code path and would otherwise cover
    for each other.
    """
    asserted.append(label)
    if len(violations) != 1:
        print(f"  FAIL {label:<62} {len(violations)} violation(s): {violations}")
        failures.append(label)
        return
    text = violations[0]
    missing = [f for f in fragments if f not in text]
    ok = not missing
    print(f"  {'ok  ' if ok else 'FAIL'} {label:<62} {text[:70]}")
    if not ok:
        failures.append(f"{label} (message lacks {missing})")


# ===========================================================================
# The rules. Every one is a pure function over (registry, packs, text) so it
# can be driven by a fixture that violates it and by the live tree, which
# must not.
# ===========================================================================

HEADING = re.compile(r"^### `([a-z][a-z0-9_]*)`$", re.M)
# The two tables both begin `| \`token\` | `, and telling them apart is the
# second cell: the summary table's is the integer run order, a parameter
# table's is a declared type. Matching on the token alone credited every
# parameter key as a behavior and made the catalogue assertion pass for a
# document that listed none of the right things.
SUMMARY_ROW = re.compile(r"^\| `([a-z][a-z0-9_]*)` \| \d+ \| ", re.M)
# Non-capturing on the type: `findall` returns a tuple per match the moment a
# pattern has two groups, and a list of tuples compared against a list of
# strings is never equal -- an assertion that fails for the wrong reason is
# only marginally better than one that cannot fail.
PARAM_ROW = re.compile(r"^\| `([a-z][a-z0-9_]*)` \| (?:int|float|str|bool) \| ",
                       re.M)
PYONEER_NAME = re.compile(r"\bpyoneer_[a-zA-Z0-9_]*")
GAME_CLASS = re.compile(r"\bGame[A-Z][A-Za-z0-9_]*")

WIDENS = {("float", "int")}
"""(parameter type, column type) pairs where the mismatch is deliberate.

`BehaviorParam.coerce` widens an int to a float, because Tiled writes `900`
for a float-typed property and calling that an authoring error would make
every whole-number float one. The reverse does NOT widen -- a float into an
int parameter raises -- so it is not symmetric and this set is not a pair of
sets.
"""


def catalogue_tokens(text: str) -> tuple[tuple[str, ...], tuple[str, ...]]:
    """(tokens with a section, tokens with a summary row) as the FILE has them.

    Two separate expressions render these in `describe_all`, so reading only
    one of them would let the other drift -- a behavior listed in the table
    and missing its section reads as documented right up until somebody
    scrolls.
    """
    return tuple(HEADING.findall(text)), tuple(SUMMARY_ROW.findall(text))


def documented_params(text: str) -> dict[str, tuple[str, ...]]:
    """behavior token -> the parameter keys its own section documents.

    Sliced by section rather than scanned whole: a parameter row belongs to
    the behavior whose heading precedes it, and a global scan would let a
    parameter documented under the wrong behavior pass.
    """
    found: dict[str, tuple[str, ...]] = {}
    marks = [(m.group(1), m.start()) for m in HEADING.finditer(text)]
    for index, (token, start) in enumerate(marks):
        end = marks[index + 1][1] if index + 1 < len(marks) else len(text)
        found[token] = tuple(PARAM_ROW.findall(text[start:end]))
    return found


def column_violations(registry, packs) -> list[str]:
    """Every actors column a behavior consumes that its genre does not declare.

    THE ASSERTION WITH TEETH. A behavior declaring
    `BehaviorParam("gravity", ..., source="actors")` is making a claim about
    the project's data model, and the claim is checkable: the pack it names in
    `genres` must have an `actors` table with a `gravity` column of a
    compatible type. Nothing else in the tree checks it -- nothing in
    `scripts/` reads `data/project/` at all, so the mismatch would surface as
    a parameter that silently took its default on every actor, forever.

    A `source="actors"` parameter on a behavior that declares NO genre is a
    violation too. `genres=()` means "any", and a column that any pack may or
    may not have is a column no pack is answerable for.
    """
    found: list[str] = []
    for spec in sorted(registry.values(), key=lambda s: s.name):
        actor_params = [p for p in spec.params if p.source == "actors"]
        if not actor_params:
            continue
        if not spec.genres:
            found.append(
                "behavior %r reads %s from the actors table but declares no "
                "genres, so no pack is answerable for the column(s). Add the "
                "genre id(s) to its BehaviorSpec."
                % (spec.name, ", ".join(repr(p.key) for p in actor_params)))
            continue
        for genre_id in spec.genres:
            pack = packs.get(genre_id)
            if pack is None:
                found.append(
                    "behavior %r declares genre %r, which is not a pack on "
                    "disk (%s)" % (spec.name, genre_id,
                                   ", ".join(sorted(packs)) or "none"))
                continue
            table = pack.table("actors")
            if table is None:
                found.append(
                    "behavior %r declares genre %r, whose pack has no 'actors' "
                    "table to read %s from"
                    % (spec.name, genre_id,
                       ", ".join(repr(p.key) for p in actor_params)))
                continue
            for param in actor_params:
                column = table.field(param.key)
                if column is None:
                    found.append(
                        "behavior %r consumes actors column %r, and genre %r "
                        "does not declare it. Add it to "
                        "editor/genres/%s/genre.json, or change the parameter "
                        "to source=\"object\"."
                        % (spec.name, param.key, genre_id, genre_id))
                elif (column.type != param.type
                      and (param.type, column.type) not in WIDENS):
                    found.append(
                        "behavior %r declares %r as %s and genre %r declares "
                        "that column as %s; an authored value would be refused "
                        "by BehaviorParam.coerce"
                        % (spec.name, param.key, param.type, genre_id,
                           column.type))
    return found


def spawn_violations(packs, registry=None) -> list[str]:
    """Every object class a pack allows that the spawn registry cannot build.

    `spawn_objects` RAISES on an unknown Type, so an object placed from a
    class the pack advertised makes the whole map unloadable -- and the editor
    validates placements against exactly this list, so the pack advertising a
    class the engine cannot build is the editor telling an author to break
    their map.
    """
    table = SPAWN_REGISTRY if registry is None else registry
    found: list[str] = []
    for pack in sorted(packs.values(), key=lambda p: p.id):
        for layer in pack.layers:
            for kind in layer.object_types:
                if kind not in table:
                    found.append(
                        "genre %r allows object class %r on layer %r, and it "
                        "is not in SPAWN_REGISTRY (%s), so an object of that "
                        "Type makes the map raise at load"
                        % (pack.id, kind, layer.name,
                           ", ".join(sorted(table)) or "empty"))
            for kind in layer.unique_types:
                if kind not in layer.object_types:
                    found.append(
                        "genre %r declares %r unique on layer %r without "
                        "allowing it there" % (pack.id, kind, layer.name))
    return found


def default_list_violations(packs, registry) -> list[str]:
    """Every class default a pack declares that would not actually work.

    Reads `GenreLayer.object_classes` -- the loaded field, not a second parse
    of the same JSON. Two readers of one file format is how a rule and the
    thing it judges drift apart.

    `editor/core/genre.py` already refuses, at pack load, everything the
    ENGINE would refuse: an unregistered token, a duplicate, a declared
    conflict, a class the layer forbids. What is left for a check is the two
    things `validate_list` structurally cannot see, because neither makes a
    map fail to load -- they make a placed object quietly not work:

      * a token gated to a DIFFERENT genre. `spec.genres` is reported by the
        behavior panel and enforced by nobody, so a platformer pack shipping
        `topdown_move` would load, materialise, attach, and not move.
      * a token whose status is not `live`. `_swap_section` already refuses
        to RECOMMEND one for exactly this reason; a pack default is a
        stronger claim than a recommendation, so it is held to the same bar.

    The unregistered-token clause is kept as well. It is unreachable through
    `genre.load` today and that is the point: it is what still catches a pack
    built any other way, and the day the loader's guard is loosened this is
    the assertion that goes red instead of the author's map.
    """
    found: list[str] = []
    for genre_id in sorted(packs):
        pack = packs[genre_id]
        for layer in pack.layers:
            for declared in layer.object_classes:
                for token in declared.behaviors:
                    spec = registry.get(token)
                    if spec is None:
                        found.append(
                            "genre %r gives object class %r the default "
                            "behavior %r, which is not registered (%s)"
                            % (genre_id, declared.type, token,
                               ", ".join(sorted(registry)) or "the registry "
                               "is empty"))
                        continue
                    if spec.genres and genre_id not in spec.genres:
                        found.append(
                            "genre %r gives object class %r the default "
                            "behavior %r, which declares genres %s -- it "
                            "would attach and do nothing"
                            % (genre_id, declared.type, token,
                               list(spec.genres)))
                    if spec.status != "live":
                        found.append(
                            "genre %r gives object class %r the default "
                            "behavior %r, whose status is %r -- a default is "
                            "a stronger claim than a recommendation, and "
                            "this one is not recommended either"
                            % (genre_id, declared.type, token, spec.status))
    return found


def vocabulary_violations(text: str, where: str, registry=None) -> list[str]:
    """Every `pyoneer_*` name in `text` that is not a real property name.

    This is the spelling guard extended to the prose. A property written into
    a .tmx under a name nothing reads does nothing at all and reports nothing
    (law 7), so a document that teaches `pyoneer_behaviours` (the British
    form, which
    the vocabulary does not use) is a document that teaches an author to write
    a dead property.
    """
    table = BEHAVIOR_REGISTRY if registry is None else registry
    known = set(layer_profile.KNOWN) | {BEHAVIORS, ACTOR}
    # The two bare prefixes are legal prose -- "the `pyoneer_` prefix is
    # load-bearing", "a stray `pyoneer_param_` nothing consumes" -- and are
    # not claims that a property by that name exists.
    prefixes = {layer_profile.PREFIX, PARAM_PREFIX}
    found: list[str] = []
    for name in sorted(set(PYONEER_NAME.findall(text))):
        if name in known or name in prefixes:
            continue
        if name.startswith(PARAM_PREFIX):
            suffix = name[len(PARAM_PREFIX):]
            if TOKEN.match(suffix):
                continue
            found.append(
                "%s writes %r, whose parameter key %r is not snake_case"
                % (where, name, suffix))
            continue
        found.append(
            "%s writes the property name %r, which is not one the engine "
            "reads. Known: %s, and %s<key>."
            % (where, name, ", ".join(sorted(known)), PARAM_PREFIX))
    return found


def rules_coverage_violations(text: str, genre_id: str, registry) -> list[str]:
    """Behaviors that claim this genre and are not named in its RULES.md.

    Only the genre-EXCLUSIVE ones. A behavior declaring `genres=()` applies
    everywhere and lives in the generated document; requiring every pack to
    restate the whole catalogue would rebuild in prose the thing that
    generation exists to stop. But a behavior that says *I am the platformer's
    body* and goes unmentioned in the platformer's rules is a behavior an AI
    reading that pack will not know to reach for -- which is the same failure
    as it not existing.
    """
    found: list[str] = []
    for spec in sorted(registry.values(), key=lambda s: s.name):
        if genre_id not in spec.genres:
            continue
        if ("`%s`" % spec.name) not in text:
            found.append(
                "behavior %r declares genre %r and %s/RULES.md never names it, "
                "so nothing reading that pack learns it exists"
                % (spec.name, genre_id, genre_id))
    return found


def missing_class_names(text: str, defined: set[str]) -> list[str]:
    """Every `Game*` class the text names that is not defined anywhere.

    A rules document that teaches a class name the tree does not have sends
    an AI to grep for it, find nothing, and invent one -- which is how a
    genre pack ends up prescribing a subclass in the same breath as telling
    you not to write subclasses.
    """
    return sorted({name for name in GAME_CLASS.findall(text)
                   if name not in defined})


def defined_names() -> set[str]:
    """Every class and function name defined under scripts/, editor/, config/.

    AST, not grep: a name in a docstring or a comment is not a definition, and
    counting one would make this rule pass for a class that only exists in
    prose -- which is the exact failure it is written to catch.
    """
    names: set[str] = set()
    roots = [os.path.join(ROOT, part) for part in ("scripts", "editor", "config")]
    roots.append(os.path.join(ROOT, "main.py"))
    for root in roots:
        walk = ([(os.path.dirname(root), [], [os.path.basename(root)])]
                if os.path.isfile(root) else os.walk(root))
        for dirpath, _dirs, files in walk:
            if "__pycache__" in dirpath:
                continue
            for name in files:
                if not name.endswith(".py"):
                    continue
                with open(os.path.join(dirpath, name), encoding="utf-8") as handle:
                    try:
                        tree = ast.parse(handle.read())
                    except SyntaxError:
                        continue
                for node in ast.walk(tree):
                    if isinstance(node, (ast.ClassDef, ast.FunctionDef)):
                        names.add(node.name)
    return names


# ===========================================================================
# What the engine has actually wired up. Derived by DRIVING it, never by
# reading a flag: a boolean somebody has to remember to flip is a boolean
# that is wrong on the commit that matters.
# ===========================================================================

class _ProbeEntity(GameEntity):
    """A GameEntity that is constructible. Filling the two abstract methods
    is the whole difference between the base class and something a check can
    stand up, and it needs no art."""

    def core_lifecycle_build(self, event=None):
        pass

    def core_input_receive(self, events=None):
        pass


class _Spy(EntityBehavior):
    """Counts the frames the drive gave it."""

    def __init__(self):
        self.calls = 0

    def update(self, entity, event):
        self.calls += 1


_SPY_SPEC = BehaviorSpec(name="probe_spy",
                         summary="Counts update calls. Never registered.",
                         factory=_Spy, order=50)


def drive_calls(frames: int, enabled: bool = True) -> int | None:
    """How many times a bound behavior's `update` ran over `frames` frames.

    None when there is no `EntityBehaviors` on the entity to attach to at all,
    which is a different answer from zero: nothing to drive versus a drive
    that does not run.

    A COUNT rather than a boolean, and driven for a caller-chosen number of
    frames, because the two ways this wire breaks look identical to a
    single-frame yes/no probe: a drive that fires once at attach and never
    again returns 1 for any frame count, and a drive that fires twice per
    frame returns 2 for one frame. Only `calls == frames` for more than one
    value of `frames` separates them from a working one.
    """
    entity = _ProbeEntity()
    holder = getattr(entity, "behaviors", None)
    if not isinstance(holder, EntityBehaviors):
        return None
    spy = _Spy()
    spy.spec = _SPY_SPEC
    holder.attach(spy)
    spy.enabled = enabled
    for _ in range(frames):
        entity.core_frame_update(PyoneerEvent(GameEventType.UPDATE,
                                              data={"delta": 1.0}))
    return spy.calls


def entity_drives_behaviors() -> bool:
    """True when `GameEntity.core_frame_update` really runs a bound behavior."""
    return drive_calls(2) == 2


def _calls(name: str, *relative: str) -> tuple[str, ...]:
    """Files under `relative` that CALL `name`, repo-relative, package excluded.

    AST rather than a substring search, and calls rather than imports. Both
    distinctions earn their keep here: `read_requests` appears in three
    docstrings under `scripts/`, and a module that imports the behavior
    package to hold an `EntityBehaviors` is not thereby a module that reads a
    map's behavior list. Counting either would report a wire that is not
    there, which is the one thing this table must never do.
    """
    package = os.path.join("game", "behavior")
    found: list[str] = []
    targets: list[str] = []
    for part in relative:
        root = os.path.join(ROOT, part)
        if os.path.isfile(root):
            targets.append(root)
            continue
        for dirpath, _dirs, files in os.walk(root):
            if "__pycache__" in dirpath or package in dirpath:
                continue
            targets.extend(os.path.join(dirpath, n) for n in files
                           if n.endswith(".py"))
    for path in targets:
        with open(path, encoding="utf-8") as handle:
            try:
                tree = ast.parse(handle.read())
            except SyntaxError:
                continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            func = node.func
            called = (func.id if isinstance(func, ast.Name)
                      else func.attr if isinstance(func, ast.Attribute) else "")
            if called == name:
                found.append(os.path.relpath(path, ROOT).replace(os.sep, "/"))
                break
    return tuple(sorted(found))


def _assigns_collision_field() -> tuple[str, ...]:
    """Files that ASSIGN `collision_field`, which is what feeds the gate.

    The annotated declaration on `GameEntity` is not an assignment of a field
    -- `self.collision_field: CollisionField | None = None` has a colon where
    this pattern wants an equals sign -- so the declaration does not count
    itself as its own consumer.
    """
    pattern = re.compile(r"\.collision_field\s*=")
    found: list[str] = []
    targets = [os.path.join(ROOT, "main.py")]
    for dirpath, _dirs, files in os.walk(os.path.join(ROOT, "scripts")):
        if "__pycache__" in dirpath:
            continue
        targets.extend(os.path.join(dirpath, n) for n in files
                       if n.endswith(".py"))
    for path in targets:
        with open(path, encoding="utf-8") as handle:
            if pattern.search(handle.read()):
                found.append(os.path.relpath(path, ROOT).replace(os.sep, "/"))
    return tuple(sorted(found))


def _input_actions() -> tuple[str, ...]:
    with open(INPUTS_PATH, encoding="utf-8") as handle:
        return tuple(sorted(json.load(handle)))


def integration_rows() -> list[tuple[str, bool, str]]:
    """(what the wire is, whether it exists, what it would cost) -- all derived."""
    entity = _ProbeEntity()
    has_holder = isinstance(getattr(entity, "behaviors", None), EntityBehaviors)
    readers = _calls("read_requests", "scripts", "main.py")
    spawners = _calls("read_requests", "scripts/loaders", "scripts/core")
    gated = _assigns_collision_field()
    actions = _input_actions()
    return [
        ("`GameEntity.behaviors` exists on a constructed entity",
         has_holder,
         "one attribute in `GameEntity.__init__`"),
        ("`GameEntity.core_frame_update` runs the drive",
         entity_drives_behaviors(),
         "one line replacing the `pass` in `game_entity.py`"),
        ("a behavior is registered",
         bool(BEHAVIOR_REGISTRY),
         "one `register(BehaviorSpec(...))` in "
         "`scripts/game/behavior/registry.py`"),
        ("a declaration is turned into attached behaviors somewhere",
         bool(readers),
         "`read_requests` + `build` + `attach_all`" if not readers else
         "done in " + ", ".join("`%s`" % r for r in readers)),
        ("a **tmx object's** `%s` property is read when it spawns" % BEHAVIORS,
         bool(spawners),
         "`read_requests(obj.properties)` in `scripts/loaders/map_loader.py`, "
         "carried on `SpawnedEntity` and attached by the binder. Until then a "
         "list authored in Tiled does nothing and only a Python caller can "
         "compose one." if not spawners else
         "read in " + ", ".join("`%s`" % s for s in spawners)),
        ("`GameEntity.collision_field` is assigned in production",
         bool(gated),
         "`field_from_map` at map load, handed to each spawned entity. Until "
         "then every body is UNGATED -- a platformer body accelerates "
         "downward forever and never lands."
         if not gated else "assigned in " + ", ".join("`%s`" % g for g in gated)),
        ("a `jump` input action exists",
         "jump" in actions,
         "one entry in `config/inputs.json`; `held()`/`pressed()` are "
         "unguarded dict indexes, so the behavior and the binding are ONE "
         "change" if "jump" not in actions else
         "`config/inputs.json` binds " + ", ".join("`%s`" % a for a in actions)),
    ]


# ===========================================================================
# The generator
# ===========================================================================

def _genre_section(packs) -> list[str]:
    lines = ["## What each genre pack declares", "",
             "Derived from `editor/genres/*/genre.json`, so a pack that gains "
             "a column gains it here. A behavior whose parameter declares "
             "`source=\"actors\"` may name any column in its genre's table "
             "below -- and only those, which is what this check enforces.", ""]
    for genre_id in sorted(packs):
        pack = packs[genre_id]
        lines.append("### `%s` -- %s" % (genre_id, pack.title))
        lines.append("")
        gated = [l.name for l in pack.layers if l.collision]
        lines.append("- **passability is authored against** %s"
                     % (", ".join("`%s` (companion `%sCollision`)" % (n, n)
                                  for n in gated) or "no layer"))
        for layer in pack.layers:
            if layer.kind != "object":
                continue
            lines.append("- **object layer `%s` allows** %s"
                         % (layer.name,
                            ", ".join("`%s`" % t for t in layer.object_types)
                            or "nothing"))
        actors = pack.table("actors")
        if actors is None:
            lines.append("- **no `actors` table**, so no `source=\"actors\"` "
                         "parameter can resolve here")
        else:
            lines.append("- **actors columns a parameter may name** %s"
                         % ", ".join("`%s` (%s)" % (f.name, f.type)
                                     for f in actors.fields))
        defaults = []
        for layer in pack.layers:
            for declared in layer.object_classes:
                defaults.append("`%s` on `%s` -> `%s`"
                                % (declared.type, layer.name,
                                   declared.behaviors_text or "nothing"))
        if defaults:
            lines.append(
                "- **default behavior lists** %s. The editor MATERIALISES "
                "these into the object's `%s` property when the object is "
                "added, so the `.tmx` stays the whole truth and the engine "
                "never has to read a pack -- `scripts/` may not import "
                "`editor/`. It is a STARTING VALUE, not a policy: edit the "
                "list on the object afterwards and your edit stands, because "
                "nothing reads the pack again."
                % (", ".join(defaults), BEHAVIORS))
        else:
            lines.append(
                "- **default behavior lists** none declared. The pack may "
                "declare them as `layers[].object_classes[].behaviors`; the "
                "editor MATERIALISES such a default into the object when the "
                "object is added, so the `.tmx` stays the whole truth and the "
                "engine never has to read a pack -- `scripts/` may not import "
                "`editor/`.")
        lines.append("")
    return lines


def _swap_section(registry) -> list[str]:
    lines = ["## Swapping one behavior list for another", "",
             "This is the whole point of the design: the same class, the same "
             "spawn entry, a different list.", ""]
    if not registry:
        lines.append(
            "There is nothing to swap yet -- the registry is empty, so every "
            "token below would raise `PyoneerAssetMissingError`. The shape it "
            "will take, with the tokens left as placeholders on purpose:")
        lines.append("")
        lines.append("```xml")
        lines.append('<object id="1" type="GamePlayer" x="64" y="96">')
        lines.append("  <properties>")
        lines.append('    <property name="%s" value="&lt;move&gt;,&lt;collide&gt;"/>'
                     % BEHAVIORS)
        lines.append('    <property name="%smove_speed" type="int" value="24"/>'
                     % PARAM_PREFIX)
        lines.append("  </properties>")
        lines.append("</object>")
        lines.append("```")
        lines.append("")
        lines.append(
            "Change the value of `%s` and the object plays differently with "
            "no code change and no new class. Nothing else about the object "
            "moves: same `type`, same `SPAWN_REGISTRY` entry, same depth."
            % BEHAVIORS)
        lines.append("")
        return lines
    ordered = sorted(registry.values(), key=lambda s: (s.order, s.name))
    neutral = [s.name for s in ordered if not s.genres]
    claimed = sorted({g for s in ordered for g in s.genres})
    lines.append("| genre | a complete, legal list |")
    lines.append("| --- | --- |")
    for genre_id in claimed:
        chosen: list[str] = []
        for spec in ordered:
            if spec.genres and genre_id not in spec.genres:
                continue
            # This column is read as a RECOMMENDATION, so it may only offer
            # what works out of the box. A `needs-host` behavior runs
            # correctly and still does nothing until the game assigns
            # something the engine never will -- and `requires` is reported,
            # never enforced, so there is no crash to reveal the mistake.
            # `authoring-only` is excluded for the plainer reason.
            if spec.status != "live":
                continue
            # Legality is decided by the engine's own rule, not by a second
            # copy of it here: a candidate is accepted only if `validate_list`
            # accepts the list it would produce. That is what keeps this table
            # from ever printing a pair the loader would refuse.
            try:
                validate_list(chosen + [spec.name], registry)
            except Exception:                              # declared conflict
                continue
            chosen.append(spec.name)
        lines.append("| `%s` | `%s` |" % (genre_id, format_list(chosen)))
    lines.append("")
    lines.append("Set the object's `%s` property to one of those values. Same "
                 "`type`, same `SPAWN_REGISTRY` entry, same depth, same class "
                 "-- only the list changes. %s"
                 % (BEHAVIORS,
                    ("%s declare no genre and so belong in any list."
                     % ", ".join("`%s`" % n for n in neutral))
                    if neutral else ""))
    lines.append("")
    return lines


def render_doc(registry=None, packs=None) -> str:
    """The whole of `docs/BEHAVIORS.md`, from the registry and the packs.

    `describe_all()` first and verbatim, so the half the engine owns is not
    paraphrased anywhere. Then the two things it cannot see: what the engine
    around it has wired, and what the packs declare.
    """
    registry = BEHAVIOR_REGISTRY if registry is None else registry
    if packs is None:
        packs = load_packs()
    lines = [describe_all(registry).rstrip("\n"), "", SENTINEL, ""]
    lines.append("## Integration status")
    lines.append("")
    rows = integration_rows()
    lines.append(WIRED if all(ok for _, ok, _ in rows[:2]) else UNWIRED)
    lines.append("")
    lines.append(
        "Every row below is measured, not declared: the drive row is produced "
        "by constructing a real `GameEntity`, attaching a behavior and running "
        "two frames. A row that says *no* is a wire that does not exist, not a "
        "wire that is merely undocumented.")
    lines.append("")
    lines.append("| the wire | at this commit | what it takes |")
    lines.append("| --- | --- | --- |")
    for what, ok, cost in rows:
        lines.append("| %s | %s | %s |" % (what, "**yes**" if ok else "no", cost))
    lines.append("")
    lines.extend(_genre_section(packs))
    lines.extend(_swap_section(registry))
    return "\n".join(lines).rstrip("\n") + "\n"


def load_packs():
    """id -> GenrePack, for every pack on disk.

    The loaded pack only, never the raw `genre.json` beside it: a file format
    with two readers in one process is the shape that lets a rule and its
    subject disagree.
    """
    return {genre_id: genre_module.load(genre_id)
            for genre_id in genre_module.available()}


# ===========================================================================
# Fixtures. Deliberately wrong, so a rule that cannot fail is visible here.
# ===========================================================================

class _Move(EntityBehavior):
    def __init__(self, gravity: float = 900.0):
        self.gravity = gravity

    def update(self, entity, event):
        pass


def _param(key, type_, default, source="actors"):
    return BehaviorParam(key, key.replace("_", " "), type_, default,
                         "Fixture.", source=source)


def _spec(name, params=(), genres=("platformer",), **kw):
    return BehaviorSpec(name=name, summary="Fixture.", factory=_Move,
                        params=tuple(params), genres=tuple(genres), **kw)


def _fixture_pack(genre_id="fixture", columns=(("gravity", "float"),),
                  object_types=("GamePlayer",)):
    return GenrePack(
        id=genre_id, title="Fixture", summary="", root="",
        layers=(GenreLayer(name="entity", kind="object",
                           object_types=tuple(object_types),
                           unique_types=()),),
        tables=(GenreTable(name="actors", title="Actors",
                           fields=tuple(GenreField(name=n, type=t)
                                        for n, t in columns)),))


PACKS = load_packs()
DEFINED = defined_names()

print("check_behavior_docs -- the paper must agree with the machinery")
print(f"  registry: {len(BEHAVIOR_REGISTRY)} behavior(s); "
      f"packs: {', '.join(sorted(PACKS))}")


if "--write" in sys.argv:
    with open(DOC_PATH, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(render_doc(BEHAVIOR_REGISTRY, PACKS))
    print(f"\nwrote {os.path.relpath(DOC_PATH, ROOT)} "
          f"({len(BEHAVIOR_REGISTRY)} behavior(s))")
    raise SystemExit(0)


DOC_EXISTS = os.path.isfile(DOC_PATH)
DOC = ""
if DOC_EXISTS:
    with open(DOC_PATH, encoding="utf-8", newline="") as handle:
        DOC = handle.read().replace("\r\n", "\n")


# ===========================================================================
print("\n1. docs/BEHAVIORS.md is exactly what the generator produces")
# ===========================================================================
expect_true("the file exists at all", DOC_EXISTS)
expect_true("its first half is byte-for-byte registry.describe_all()",
            DOC.startswith(describe_all(BEHAVIOR_REGISTRY).rstrip("\n")))
expect("...and the whole file matches the generator",
       DOC, render_doc(BEHAVIOR_REGISTRY, PACKS))
expect("the boundary between the two halves is marked exactly once",
       DOC.count(SENTINEL), 1)
# Not implied by the equality above, unlike the count: if `describe_all` ever
# emitted this marker itself the boundary would be ambiguous and the prefix
# assertion would be reading the wrong half of the file.
expect("...and the generated half never emits the marker itself",
       describe_all(BEHAVIOR_REGISTRY).count(SENTINEL), 0)
expect_true("the file names the command that regenerates it",
            REGENERATE in DOC)


# ===========================================================================
print("\n2. the catalogue in the FILE names exactly the registered behaviors")
# ===========================================================================
_sections, _rows = catalogue_tokens(DOC)
expect("every behavior with a section is registered, and vice versa",
       sorted(_sections), sorted(BEHAVIOR_REGISTRY))
expect("...and the summary table lists the same set",
       sorted(_rows), sorted(BEHAVIOR_REGISTRY))
expect("no behavior is listed twice", len(set(_sections)), len(_sections))

# TEETH: the two assertions above pass for as long as the live document is
# correct, and say nothing about the reader. Drive the same function over a
# fixture registry, and over a document damaged in each of the two ways.
_fix_registry = {"zzz_late": _spec("zzz_late", order=90),
                 "aaa_early": _spec("aaa_early", order=10)}
_fix_doc = render_doc(_fix_registry, PACKS)
_fs, _fr = catalogue_tokens(_fix_doc)
expect("fixture: a populated registry produces a section per behavior",
       sorted(_fs), ["aaa_early", "zzz_late"])
expect("fixture: ...and a summary row per behavior", sorted(_fr),
       ["aaa_early", "zzz_late"])
expect("fixture: a doc missing one section is detected",
       sorted(catalogue_tokens(_fix_doc.replace("### `zzz_late`", "### zzz"))[0]),
       ["aaa_early"])
expect("fixture: a doc missing one summary row is detected",
       sorted(catalogue_tokens(_fix_doc.replace("| `zzz_late` | 90",
                                                "| zzz | 90"))[1]),
       ["aaa_early"])
# Order, not just membership: `aaa_early` (order 10) must print before
# `zzz_late` (order 90), which alphabetical order agrees with -- so the probe
# also runs the reverse pair, where it does not.
expect("fixture: the catalogue is in declared order, not alphabetical",
       list(catalogue_tokens(render_doc(
           {"aaa_late": _spec("aaa_late", order=90),
            "zzz_early": _spec("zzz_early", order=10)}, PACKS))[0]),
       ["zzz_early", "aaa_late"])


# ===========================================================================
print("\n3. every parameter the file documents is one its behavior declares")
# ===========================================================================
for _token, _keys in documented_params(DOC).items():
    expect(f"{_token}: documented parameters are the declared ones",
           sorted(_keys), sorted(BEHAVIOR_REGISTRY[_token].param_keys))

# TWO behaviors with DIFFERENT parameters, because a reader that scans the
# whole document instead of one section still answers correctly when there is
# only one section to confuse it with. `early` must not be credited with
# `late`'s parameter, and it is the only probe that can tell the two readers
# apart.
_pdoc = render_doc(
    {"early": _spec("early", (_param("gravity", "float", 900.0),), order=10),
     "late": _spec("late", (_param("hop", "int", 3, "object"),), order=90)},
    PACKS)
expect("fixture: a behavior's parameters are documented under its own heading",
       sorted(documented_params(_pdoc)["early"]), ["gravity"])
expect("fixture: a later behavior's parameter is not credited to an earlier one",
       sorted(documented_params(_pdoc)["late"]), ["hop"])
expect("fixture: a parameter under the WRONG heading is not credited",
       documented_params(_pdoc.replace("### `early`", "### `other`")).get("early"),
       None)


# ===========================================================================
print("\n4. every actors column a behavior consumes is declared by its genre")
# ===========================================================================
expect("the live registry against the real packs: nothing unbacked",
       column_violations(BEHAVIOR_REGISTRY, PACKS), [])

# TEETH. The line above compares [] with [] for as long as the live tree is
# clean, which is every day until it is not. Each fixture below violates
# exactly one clause.
expect("fixture: a column the genre DOES declare is clean",
       column_violations({"g": _spec("g", (_param("gravity", "float", 900.0),),
                                     genres=("platformer",))}, PACKS), [])
expect_reports(
    "fixture: the same column against a genre that lacks it is reported",
    column_violations({"g": _spec("g", (_param("gravity", "float", 900.0),),
                                  genres=("topdown_rpg",))}, PACKS),
    "'g'", "'gravity'", "'topdown_rpg'", "genre.json")
expect("fixture: a source=\"object\" parameter needs no column at all",
       column_violations({"g": _spec("g", (_param("nowhere", "int", 1, "object"),),
                                     genres=("topdown_rpg",))}, PACKS), [])
expect_reports(
    "fixture: an int parameter over a float column is a refused coercion",
    column_violations({"g": _spec("g", (_param("gravity", "int", 900),),
                                  genres=("platformer",))}, PACKS),
    "'gravity'", "int", "float")
expect("fixture: a float parameter over an int column widens, as coerce does",
       column_violations({"g": _spec("g", (_param("coyote_ms", "float", 90.0),),
                                     genres=("platformer",))}, PACKS), [])
expect_reports(
    "fixture: a genre id with no pack on disk is reported",
    column_violations({"g": _spec("g", (_param("gravity", "float", 900.0),),
                                  genres=("shmup",))}, PACKS),
    "'g'", "'shmup'", "not a pack on disk")
expect_reports(
    "fixture: an actors parameter with no declared genre is reported",
    column_violations({"g": _spec("g", (_param("gravity", "float", 900.0),),
                                  genres=())}, PACKS),
    "'g'", "'gravity'", "declares no genres")
expect("fixture: a behavior with no actors parameters needs no genre",
       column_violations({"g": _spec("g", (_param("x", "int", 1, "object"),),
                                     genres=())}, PACKS), [])
expect_reports(
    "fixture: a genre whose pack has no actors table is reported",
    column_violations(
        {"g": _spec("g", (_param("gravity", "float", 900.0),),
                    genres=("fixture",))},
        {"fixture": GenrePack(id="fixture", title="F", summary="", root="")}),
    "'g'", "no 'actors' table")


# ===========================================================================
print("\n5. a pack's object_types are all spawnable")
# ===========================================================================
expect("the real packs advertise only classes SPAWN_REGISTRY can build",
       spawn_violations(PACKS), [])
expect_reports(
    "fixture: a class the registry cannot build is reported",
    spawn_violations({"f": _fixture_pack(object_types=("GameFloorEntity",))}),
    "'fixture'", "'GameFloorEntity'", "raise at load")
expect("fixture: a class it CAN build is clean",
       spawn_violations({"f": _fixture_pack(object_types=("GamePlayer",))}), [])
expect_reports(
    "fixture: a unique class the layer does not allow is reported",
    spawn_violations({"f": GenrePack(
        id="f", title="F", summary="", root="",
        layers=(GenreLayer(name="entity", kind="object",
                           object_types=("GamePlayer",),
                           unique_types=("GameScene",)),))}),
    "'f'", "'GameScene'", "without allowing it")

# The fixtures below build `GenrePack` objects DIRECTLY rather than going
# through `genre.load`, and that is deliberate: `editor/core/genre.py` refuses
# an unregistered token at load, so a pack loaded from disk can no longer carry
# one. Bypassing the loader is the only way to prove this rule still bites --
# and it is exactly the case it exists for, since the loader's guard is one
# edit away from being loosened.
def _default_pack(genre_id="f", behaviors=(), object_type="GamePlayer"):
    return GenrePack(
        id=genre_id, title="F", summary="", root="",
        layers=(GenreLayer(
            name="entity", kind="object", object_types=("GamePlayer",),
            object_classes=(GenreObjectClass(type=object_type,
                                             behaviors=tuple(behaviors)),)),))


expect("no pack declares a default behavior list it cannot resolve",
       default_list_violations(PACKS, BEHAVIOR_REGISTRY), [])
expect("the real packs' defaults are not empty, so that line means something",
       sorted(c.type for p in PACKS.values() for l in p.layers
              for c in l.object_classes), ["GamePlayer", "GamePlayer"])
expect_reports(
    "fixture: a declared default naming an unregistered token is reported",
    default_list_violations({"f": _default_pack(behaviors=("ghost_move",))},
                            BEHAVIOR_REGISTRY),
    "'f'", "'ghost_move'", "not registered")
expect("fixture: a declared default naming a REGISTERED token is clean",
       default_list_violations({"f": _default_pack(behaviors=("real",))},
                               {"real": _spec("real", genres=())}), [])
expect_reports(
    "fixture: a default gated to ANOTHER genre is reported -- it would "
    "attach and silently do nothing",
    default_list_violations({"f": _default_pack(behaviors=("real",))},
                            {"real": _spec("real", genres=("other",))}),
    "'f'", "'real'", "would attach and do nothing")
expect("fixture: the same token under the genre it declares is clean",
       default_list_violations({"f": _default_pack(behaviors=("real",))},
                               {"real": _spec("real", genres=("f",))}), [])
expect_reports(
    "fixture: a default whose spec is not live is reported",
    default_list_violations({"f": _default_pack(behaviors=("real",))},
                            {"real": _spec("real", genres=(),
                                           status="authoring-only")}),
    "'f'", "'real'", "'authoring-only'")
expect("fixture: a pack with no object_classes at all reports nothing",
       default_list_violations(
           {"f": GenrePack(id="f", title="F", summary="", root="",
                           layers=(GenreLayer(name="entity", kind="object"),))},
           BEHAVIOR_REGISTRY), [])


# ===========================================================================
print("\n6. every pyoneer_* name in the docs is a real property name")
# ===========================================================================
RULES = {}
for _id in sorted(PACKS):
    _path = os.path.join(GENRES_DIR, _id, "RULES.md")
    with open(_path, encoding="utf-8", newline="") as handle:
        RULES[_id] = handle.read().replace("\r\n", "\n")

expect("docs/BEHAVIORS.md spells every property name correctly",
       vocabulary_violations(DOC, "BEHAVIORS.md"), [])
for _id, _text in RULES.items():
    expect(f"{_id}/RULES.md spells every property name correctly",
           vocabulary_violations(_text, f"{_id}/RULES.md"), [])

expect_reports(
    "fixture: the British spelling of the list property is reported",
    vocabulary_violations("write pyoneer_behaviours on the object", "fix"),
    "pyoneer_behaviours", "not one the engine reads")
expect_reports(
    "fixture: an invented property name is reported",
    vocabulary_violations("set pyoneer_gravity to 900", "fix"),
    "pyoneer_gravity", "not one the engine reads")
expect_reports(
    "fixture: a parameter override with a non-token key is reported",
    vocabulary_violations("set pyoneer_param_MoveSpeed", "fix"),
    "pyoneer_param_MoveSpeed", "not snake_case")
expect("fixture: a well-formed parameter override is clean",
       vocabulary_violations("set %smove_speed" % PARAM_PREFIX, "fix"), [])
expect("fixture: a layer capability the engine really reads is clean",
       vocabulary_violations("%s and %s" % (layer_profile.PASSABILITY,
                                            layer_profile.RENDERS), "fix"), [])


# ===========================================================================
print("\n7. both RULES.md files are honest about what exists")
# ===========================================================================
for _id, _text in RULES.items():
    expect_true(f"{_id}/RULES.md sends the reader to the generated document",
                "docs/BEHAVIORS.md" in _text)
    expect_true(f"{_id}/RULES.md names the regeneration command",
                REGENERATE in _text)
    expect(f"{_id}/RULES.md claims a behavior exists only when one does",
           EMPTY_MARKER in _text, not BEHAVIOR_REGISTRY)
    expect(f"{_id}/RULES.md names no Game* class the tree does not define",
           missing_class_names(_text, DEFINED), [])
    expect(f"{_id}/RULES.md names every behavior that claims {_id}",
           rules_coverage_violations(_text, _id, BEHAVIOR_REGISTRY), [])

expect_reports(
    "fixture: a genre-specific behavior missing from its rules is reported",
    rules_coverage_violations("nothing here", "platformer",
                              {"g": _spec("g", genres=("platformer",))}),
    "'g'", "'platformer'", "never names it")
expect("fixture: ...and naming it satisfies the rule",
       rules_coverage_violations("use `g` for this", "platformer",
                                 {"g": _spec("g", genres=("platformer",))}), [])
expect("fixture: a behavior for ANOTHER genre is not demanded here",
       rules_coverage_violations("nothing here", "topdown_rpg",
                                 {"g": _spec("g", genres=("platformer",))}), [])
expect("fixture: a bare mention without backticks does not count as naming it",
       len(rules_coverage_violations("use g for this", "platformer",
                                     {"g": _spec("g", genres=("platformer",))})),
       1)

expect("fixture: a rules file teaching an absent class is reported",
       missing_class_names("write a `GamePlatformerBody` that owns velocity.",
                           DEFINED),
       ["GamePlatformerBody"])
expect("fixture: a class the tree really defines is clean",
       missing_class_names("`GamePlayer` and `GameEntity` and `GameComponent`",
                           DEFINED), [])
expect_true("fixture: the naming placeholder is not mistaken for a class",
            not missing_class_names("name it `Game<Thing>Behavior`", DEFINED))


# ===========================================================================
print("\n8. the integration status in the file matches what the code does")
# ===========================================================================
_wired = entity_drives_behaviors()
expect("the file's WIRED banner appears only when the drive really runs",
       WIRED in DOC, _wired)
expect("...and the NOT WIRED banner only when it does not",
       UNWIRED in DOC, not _wired)
expect("exactly one of the two banners is present",
       (WIRED in DOC) + (UNWIRED in DOC), 1)
# The banner is derived from the same probe, so comparing the banner against
# the probe would be circular. The teeth are that the FILE ON DISK is compared
# against a LIVE probe: wire or un-wire the drive without regenerating and the
# pair above goes red.
#
# These three measure the drive itself rather than restating the banner. Each
# separates a distinct broken drive that a yes/no probe reports as working:
expect("no frames driven, no calls -- the drive does not fire at attach time",
       drive_calls(0), 0)
expect("three frames driven, three calls -- exactly one per frame",
       drive_calls(3), 3)
expect("...and a disabled behavior is skipped, not merely counted",
       drive_calls(3, enabled=False), 0)

_jump = "jump" in _input_actions()
expect("the file reports the jump binding as it actually is",
       "| a `jump` input action exists | **yes** |" in DOC
       or "| a `jump` input action exists | no |" in DOC, True)
expect("...and reports it correctly",
       "| a `jump` input action exists | %s |"
       % ("**yes**" if _jump else "no") in DOC, True)


# ===========================================================================
print("\n9. summary")
# ===========================================================================
print(f"\nassertions             : {len(asserted)}")
print(f"registry at HEAD       : {len(BEHAVIOR_REGISTRY)} behavior(s)")
print(f"genre packs            : {len(PACKS)}")
print(f"BEHAVIORS.md           : {len(DOC.splitlines())} lines")
print(f"drive wired            : {_wired}")
_dupes = sorted({label for label in asserted if asserted.count(label) > 1})
if _dupes:
    print(f"  FAIL duplicate assertion labels: {_dupes}")
    failures.extend(_dupes)

if failures:
    print(f"\nFAILED ({len(failures)}):")
    for item in failures:
        print(f"  - {item}")
    print(f"\nIf a BehaviorSpec or a genre pack changed, regenerate first:\n"
          f"    {REGENERATE}")
    raise SystemExit(1)
print("\nALL BEHAVIOR DOC CHECKS PASS")
