"""Generate the two-tier code map, and the #TAG index every doc addresses by.

    .venv/Scripts/python.exe tools/gen_map.py            # verify, exit 1 on drift
    .venv/Scripts/python.exe tools/gen_map.py --write    # regenerate
    .venv/Scripts/python.exe tools/gen_map.py --tags     # print the tag index

WHY THIS IS GENERATED AND NOT WRITTEN
-------------------------------------
A hand-written index over 130 modules is dead in a week. `docs/history/ORPHANS.md` is
what that looks like after one, and the nine documentation sites that stated
the opposite of a shipped wire in one review pass are what it looks like after
three. The strongest pattern already in this tree is `describe_all` ->
`docs/BEHAVIORS.md`: a document that cannot describe a behavior that does not
exist. This applies the same rule to the shape of the code itself. Nothing
below is typed by a human, so nothing below can be wrong about what exists.

WHY A #TAG AND NOT A LINE NUMBER
--------------------------------
Measured, and the reason this file exists: `CLAUDE.md`'s anchor table used to
pin quoted source lines by `FILE:LINE`. A five-line docstring edit above one of
them turned `check_docs` red --

    game_entity.py:236 no longer contains 'if field is None or bit is None'
    -- it moved to line 241

The anchor was not wrong. The document was not stale. Nothing about the
documented fact had changed. A line number is an address that every edit above
it invalidates; a `#TAG:` is an address that survives one. So a document says
`#TAG:GameEntity.allowed_move` and a checker re-derives the line every run.

THE TWO TIERS, AND WHY THERE ARE TWO
------------------------------------
`docs/MAP.md`          TIER 1. One line per module, class and public function,
                       with `file:line` and a tag. Read it FIRST, always. It is
                       a gist: enough to know what exists and where, never
                       enough to write code against.
`docs/map/<mod>.md`    TIER 2. One file per module: full signatures with args
                       and defaults, return annotations where declared, the
                       first docstring line, module constants and every method.
                       Loaded ONLY when that module is being touched.

Loading every tier-2 file at once costs more than reading the source and
defeats the entire point. `docs/MAP.md` says so in its own preamble, and
`tools/check_docs.py` measures both files' sizes so the claim stays true.

WHAT IS MAPPED
--------------
`ROOTS` below: the code a game or an editor feature is written against.
`tools/` is deliberately NOT mapped -- a check module is read whole or not at
all, and its roster is already generated into `docs/CHECKS.md`. That exclusion
is a constant here rather than a habit, and `check_docs` asserts the mapped
roots are covered in BOTH directions: no module without a map, no map without
a module.
"""
from __future__ import annotations

import _bootstrap  # noqa: F401  (must precede engine imports)

import argparse
import ast
import os
import re
import sys
from dataclasses import dataclass, field

ROOT = _bootstrap.REPO_ROOT

ROOTS = ("config", "demos", "editor", "main.py", "scripts")
"""What the map covers. See the module docstring for what it does not."""

INDEX_REL = "docs/MAP.md"
TIER2_DIR = "docs/map"

REGENERATE = ".venv/Scripts/python.exe tools/gen_map.py --write"

BANNER = (
    "<!-- pyoneer-doc: L1 -->\n"
    "<!-- GENERATED by tools/gen_map.py. Do not edit. "
    "Regenerate: %s -->\n" % REGENERATE)

TAG = "#TAG:"

TAG_VALUE = re.compile(r"[A-Za-z0-9_](?:[A-Za-z0-9_./]*[A-Za-z0-9_])?")
"""What a tag value may contain: names, dots, slashes; never a trailing dot.

One expression for all four shapes -- `ClassName`, `function_name`,
`Owner.method`, `path/to/module.py` -- because a grammar that tried to tell a
`topic_slug` from a `function_name` would be a fifth rule nobody remembers,
and the real proof that a tag is valid is that it RESOLVES, which
`tools/check_docs.py` asserts against this file's index. The trailing-character
clause is what stops `see #TAG:GameEntity.` from claiming the tag
`GameEntity.`, which resolves nowhere and would fail for a typographical
reason.
"""

# The tag scanner must not match its own documentation. `#TAG:<Thing>` with
# angle brackets is the escape a document uses to SHOW the syntax without
# claiming the tag exists, and it is unmatched by TAG_REF for that reason.
TAG_REF = re.compile(re.escape(TAG) + r"(" + TAG_VALUE.pattern + r")")

GIST = 62
"""Hard cut for a tier-1 gist. Tier 1 is a gist or it is not tier 1."""


# ---------------------------------------------------------------------------
# Reading the tree
# ---------------------------------------------------------------------------

@dataclass
class Entry:
    """One addressable thing: a class, a function, a method or a constant."""
    kind: str                       # "class" | "def" | "method" | "const"
    name: str
    relpath: str
    lineno: int
    end_lineno: int
    signature: str = ""             # "" for a constant
    returns: str = ""               # "" when undeclared
    doc: str = ""                   # first docstring line, "" when none
    owner: str = ""                 # the class, for a method
    bases: tuple[str, ...] = ()
    decorators: tuple[str, ...] = ()
    tag: str = ""                   # filled by `assign_tags`

    @property
    def public(self) -> bool:
        return not self.name.startswith("_")


@dataclass
class Module:
    relpath: str
    dotted: str
    doc: str = ""
    lines: int = 0
    imports: tuple[str, ...] = ()   # first-party only
    entries: list[Entry] = field(default_factory=list)
    tag: str = ""

    @property
    def package(self) -> str:
        head = os.path.dirname(self.relpath)
        return head or "."

    @property
    def classes(self) -> list[Entry]:
        return [e for e in self.entries if e.kind == "class"]

    @property
    def functions(self) -> list[Entry]:
        return [e for e in self.entries if e.kind == "def"]

    @property
    def constants(self) -> list[Entry]:
        return [e for e in self.entries if e.kind == "const"]

    def methods_of(self, owner: str) -> list[Entry]:
        return [e for e in self.entries if e.kind == "method" and e.owner == owner]


def _first_line(node) -> str:
    """The docstring's first LINE, squeezed. Never a paragraph.

    A tier-1 entry that carries a paragraph is a tier-2 entry in the wrong
    file, and this repository's whole complaint about documentation is that it
    grows until nobody reads it.
    """
    text = ast.get_docstring(node, clean=True) or ""
    for raw in text.split("\n"):
        line = " ".join(raw.split())
        if line:
            return line
    return ""


def _decorators(node) -> tuple[str, ...]:
    out = []
    for dec in node.decorator_list:
        try:
            out.append(ast.unparse(dec))
        except Exception:                                    # pragma: no cover
            out.append("?")
    return tuple(out)


def _signature(node) -> tuple[str, str]:
    """(args rendered with defaults, return annotation or "")."""
    try:
        args = ast.unparse(node.args)
    except Exception:                                        # pragma: no cover
        args = "..."
    returns = ""
    if node.returns is not None:
        try:
            returns = ast.unparse(node.returns)
        except Exception:                                    # pragma: no cover
            returns = "?"
    return args, returns


def _const_names(node) -> list[str]:
    """Module-level PUBLIC UPPER_CASE assignment targets.

    Upper case only, and that is a judgement the tree earns: a lower-case
    module-level assignment here is a cached singleton or a re-export, while
    the UPPER ones are the file-format strings, the registries and the bit
    masks -- exactly the things a document quotes and therefore exactly the
    things that need an address.
    """
    names = []
    if isinstance(node, ast.Assign):
        names = [t.id for t in node.targets if isinstance(t, ast.Name)]
    elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
        names = [node.target.id]
    return [n for n in names if n.isupper() and not n.startswith("_")]


def _first_party(tree: ast.Module) -> tuple[str, ...]:
    """Dotted first-party module names this module imports.

    Only the repository's own packages. Third-party noise (`pygame`, `PySide6`)
    is uniform and says nothing; a first-party import list is the one thing
    that makes law 2 -- `scripts/` may never import `editor/` -- auditable
    from a document instead of from a grep.
    """
    heads = set(ROOTS) - {"main.py"} | {"main"}
    found = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.split(".")[0] in heads:
                    found.add(alias.name)
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            if node.module.split(".")[0] in heads:
                found.add(node.module)
    return tuple(sorted(found))


def source_files() -> list[str]:
    """Every mapped `.py`, repo-relative with forward slashes, sorted."""
    found: list[str] = []
    for root in ROOTS:
        full = os.path.join(ROOT, root.replace("/", os.sep))
        if os.path.isfile(full):
            found.append(root)
            continue
        for dirpath, dirs, files in os.walk(full):
            dirs[:] = sorted(d for d in dirs if d != "__pycache__")
            for name in sorted(files):
                if name.endswith(".py"):
                    rel = os.path.relpath(os.path.join(dirpath, name), ROOT)
                    found.append(rel.replace(os.sep, "/"))
    return sorted(found)


def read_source(relpath: str) -> str:
    with open(os.path.join(ROOT, relpath.replace("/", os.sep)),
              encoding="utf-8", newline="") as handle:
        return handle.read().replace("\r\n", "\n")


def parse_module(relpath: str) -> Module:
    return parse_text(relpath, read_source(relpath))


def parse_text(relpath: str, text: str) -> Module:
    """The AST facts for one module, from TEXT rather than from disk.

    Split out from `parse_module` so a check can drive this generator over a
    fixture it wrote itself. Every rule here would otherwise be asserted only
    against the live tree -- and "the renderer prints the signature it read" is
    exactly the kind of claim that passes vacuously when the only thing that
    can prove it is the same tree it was read from.
    """
    dotted = relpath[:-len(".py")].replace("/", ".")
    module = Module(relpath=relpath, dotted=dotted,
                    lines=len(text.split("\n")))
    try:
        tree = ast.parse(text)
    except SyntaxError:                                      # pragma: no cover
        return module
    module.doc = _first_line(tree)
    module.imports = _first_party(tree)
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            bases = []
            for base in node.bases:
                try:
                    bases.append(ast.unparse(base))
                except Exception:                            # pragma: no cover
                    bases.append("?")
            module.entries.append(Entry(
                kind="class", name=node.name, relpath=relpath,
                lineno=node.lineno, end_lineno=node.end_lineno,
                doc=_first_line(node), bases=tuple(bases),
                decorators=_decorators(node)))
            for child in node.body:
                if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    args, returns = _signature(child)
                    module.entries.append(Entry(
                        kind="method", name=child.name, relpath=relpath,
                        lineno=child.lineno, end_lineno=child.end_lineno,
                        signature=args, returns=returns,
                        doc=_first_line(child), owner=node.name,
                        decorators=_decorators(child)))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            args, returns = _signature(node)
            module.entries.append(Entry(
                kind="def", name=node.name, relpath=relpath,
                lineno=node.lineno, end_lineno=node.end_lineno,
                signature=args, returns=returns, doc=_first_line(node),
                decorators=_decorators(node)))
        else:
            for name in _const_names(node):
                module.entries.append(Entry(
                    kind="const", name=name, relpath=relpath,
                    lineno=node.lineno,
                    end_lineno=getattr(node, "end_lineno", node.lineno)))
    return module


# ---------------------------------------------------------------------------
# The tags
# ---------------------------------------------------------------------------

def assign_tags(modules: list[Module]) -> None:
    """Give every module and entry its tag value, in place.

    THE RULE, and it is one sentence: a tag is the thing's own bare name,
    qualified by its module stem only when two things in the tree share that
    name. Bare by default is not laziness -- an agent looking up `GameEntity`
    knows the class name and does not yet know the module, so a scheme that
    demanded `game_entity.GameEntity` would demand the answer as the question.

    A method is always `Owner.name`: a bare `update` is claimed by 18 classes
    here and a tag that returns 18 lines is not an address. A property's setter
    takes `Owner.name.setter`, read straight off its own `@name.setter`
    decorator -- a getter and its setter are two definitions of one attribute,
    and naming them alike would make the single most common shape in this tree
    (30 pairs) the single most common tag collision.
    """
    claims: dict[str, int] = {}
    for module in modules:
        for entry in module.entries:
            if entry.kind != "method":
                claims[entry.name] = claims.get(entry.name, 0) + 1

    def qualify(module: Module, name: str) -> str:
        if claims.get(name, 0) < 2:
            return name
        stem = os.path.basename(module.relpath)[:-len(".py")]
        return "%s.%s" % (stem, name)

    for module in modules:
        module.tag = module.relpath                 # unique by construction
        owners: dict[str, str] = {}
        for entry in module.entries:
            if entry.kind == "class":
                entry.tag = qualify(module, entry.name)
                owners[entry.name] = entry.tag
            elif entry.kind in ("def", "const"):
                entry.tag = qualify(module, entry.name)
        for entry in module.entries:
            if entry.kind != "method":
                continue
            accessor = ""
            for dec in entry.decorators:
                head, _, kind = dec.partition(".")
                if head == entry.name and kind in ("setter", "getter", "deleter"):
                    accessor = "." + kind
            entry.tag = "%s.%s%s" % (owners.get(entry.owner, entry.owner),
                                     entry.name, accessor)

    # Anything still doubled -- a stem collision (two `errors.py`, two
    # `input.py`, sixteen `__init__.py`) or a name genuinely defined twice in
    # one scope -- is resolved deterministically rather than silently
    # deduplicated. A tag resolving to two places is the ONE failure this whole
    # scheme exists to prevent, so the resolution is total: qualify by the
    # dotted module, and if that is still not enough, number the repeats in
    # source order.
    def resolve(pick) -> None:
        groups: dict[str, list[Entry]] = {}
        for module in modules:
            for entry in module.entries:
                groups.setdefault(entry.tag, []).append(entry)
        for tag, entries in groups.items():
            if len(entries) < 2:
                continue
            for index, entry in enumerate(entries):
                entry.tag = pick(entry, index)

    dotted_of = {m.relpath: m.dotted for m in modules}

    def by_module(entry: Entry, index: int) -> str:
        # Rebuilt from the entry's own parts, never from the stem-qualified tag
        # it already carries -- `dotted + tag` would spell the stem twice.
        stem = os.path.basename(entry.relpath)[:-len(".py")]
        bare = entry.tag[len(stem) + 1:] if entry.tag.startswith(stem + ".") \
            else entry.tag
        return "%s.%s" % (dotted_of[entry.relpath], bare)

    def by_order(entry: Entry, index: int) -> str:
        return entry.tag if index == 0 else "%s.%d" % (entry.tag, index + 1)

    resolve(by_module)
    resolve(by_order)


@dataclass(frozen=True)
class TagSite:
    """Where a tag points, and how much of the file it speaks for."""
    tag: str
    kind: str
    name: str
    relpath: str
    lineno: int
    end_lineno: int

    @property
    def address(self) -> str:
        return "%s:%d" % (self.relpath, self.lineno)


def tag_index(modules: list[Module] | None = None) -> dict[str, TagSite]:
    """tag -> the one place it points. Every module, entry and constant."""
    modules = load() if modules is None else modules
    index: dict[str, TagSite] = {}
    for module in modules:
        index[module.tag] = TagSite(module.tag, "module", module.relpath,
                                    module.relpath, 1, module.lines)
        for entry in module.entries:
            index[entry.tag] = TagSite(entry.tag, entry.kind, entry.name,
                                       entry.relpath, entry.lineno,
                                       entry.end_lineno)
    return index


_CACHE: list[Module] | None = None


def load(refresh: bool = False) -> list[Module]:
    """Every mapped module, parsed and tagged. Cached: the walk is not free."""
    global _CACHE
    if _CACHE is None or refresh:
        modules = [parse_module(rel) for rel in source_files()]
        assign_tags(modules)
        _CACHE = modules
    return _CACHE


# ---------------------------------------------------------------------------
# Source-side tags: a `#TAG:` comment an author placed at a site by hand
# ---------------------------------------------------------------------------

def source_tags() -> list[tuple[str, str, int, str]]:
    """(tag, relpath, lineno, the whole line) for every `#TAG:` in the tree.

    These are the hand-placed ones -- the stable address a document uses when
    it needs to quote a line that is not itself a definition. The generated
    tags need no comment in the source; this is the escape hatch for the rest,
    and it is why `CLAUDE.md` can pin a sentence inside a docstring without
    naming a line number.
    """
    found: list[tuple[str, str, int, str]] = []
    for rel in source_files():
        text = read_source(rel)
        if TAG not in text:
            continue
        for number, line in enumerate(text.split("\n"), 1):
            for match in TAG_REF.finditer(line):
                found.append((match.group(1), rel, number, line))
    return found


# ---------------------------------------------------------------------------
# Tier 1 -- docs/MAP.md
# ---------------------------------------------------------------------------

def _cut(text: str, width: int = GIST) -> str:
    text = " ".join(text.split())
    if len(text) <= width:
        return text
    return text[:width - 1].rstrip() + "…"


def _tier1_line(entry: Entry) -> str:
    """One symbol, one line, tag FIRST.

    Tag first because this line's whole job is to be the result of
    `grep -rn "#TAG:GameEntity"`: the tag is the query, so it reads as the
    query's answer, and the address that follows is what the reader wanted.
    The symbol's own name is not repeated -- for everything but a collided
    name the tag IS the name, and 470 repetitions of it is a kilobyte the
    file-that-is-always-read cannot justify. Neither is the directory: the
    module line directly above carries the full path, the tier-2 file carries
    it again, and a grep for the tag hits BOTH files, so the basename here is
    a disambiguator rather than an address.
    """
    kind = "class" if entry.kind == "class" else "def"
    head = "%s%s %s %s:%d" % (TAG, entry.tag, kind,
                              os.path.basename(entry.relpath), entry.lineno)
    gist = _cut(entry.doc, 46)
    return head + ("  · " + gist if gist else "")


def render_index(modules: list[Module] | None = None) -> str:
    modules = load() if modules is None else modules
    counts = {
        "modules": len(modules),
        "classes": sum(len(m.classes) for m in modules),
        "functions": sum(len([e for e in m.functions if e.public]) for m in modules),
        "methods": sum(len([e for e in m.entries if e.kind == "method"]) for m in modules),
        "constants": sum(len(m.constants) for m in modules),
    }
    out = [BANNER.rstrip("\n"), "",
           "# Map — tier 1, the gist", "",
           "**Read this whole file, and read it before you read any source.** "
           "It is the index: what exists, and where. It is deliberately not "
           "enough to write code against.", "",
           "Three ways down from here, cheapest first:", "",
           "| you want | do this | costs |", "|---|---|---|",
           "| one signature | `grep -rn \"%sGameEntity\"` — returns the "
           "definition line AND every document that cites it | nothing |" % TAG,
           "| to touch one module | open its tier-2 file: `docs/map/` + the "
           "module path with `/` and `.py` replaced by `.` + `.md`, so "
           "`scripts/core/depth.py` is [`docs/map/scripts.core.depth.md`]"
           "(map/scripts.core.depth.md) | ~1 page |",
           "| all of it | do not. Loading every tier-2 file costs more than "
           "reading the source, which is the exact failure two tiers exist to "
           "prevent | ~%dk |" % (sum(len(render_module(m)) for m in modules)
                                 // 4000), "",
           "Generated by `tools/gen_map.py` from the AST, so no line here can "
           "name something that does not exist, and no line here has to be "
           "maintained. Regenerate after any structural edit:", "",
           "    " + REGENERATE, "",
           "Covers `%s`. It does **not** cover `tools/` — a check module is "
           "read whole or not at all, and the roster is generated into "
           "[`CHECKS.md`](CHECKS.md)." % "`, `".join(ROOTS), "",
           "%d modules · %d classes · %d public functions · %d methods · "
           "%d constants. Methods and constants are **tier 2 only** — they "
           "still carry tags, and the tag is what you grep."
           % (counts["modules"], counts["classes"], counts["functions"],
              counts["methods"], counts["constants"]), ""]

    package = None
    for module in modules:
        if module.package != package:
            if package is not None:
                out += ["```", ""]
            package = module.package
            out += ["## `%s`" % package, "", "```"]
        gist = _cut(module.doc, 74)
        out.append("%s%s  %d line%s%s"
                   % (TAG, module.tag, module.lines,
                      "" if module.lines == 1 else "s",
                      "  · " + gist if gist else ""))
        rows = module.classes + [e for e in module.functions if e.public]
        for entry in sorted(rows, key=lambda e: e.lineno):
            out.append("  " + _tier1_line(entry))
    out += ["```", ""]
    return "\n".join(out).rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# Tier 2 -- docs/map/<dotted>.md
# ---------------------------------------------------------------------------

def tier2_rel(module: Module) -> str:
    return "%s/%s.md" % (TIER2_DIR, module.dotted)


def _render_callable(entry: Entry) -> list[str]:
    decorated = "".join("@%s " % d for d in entry.decorators)
    sig = "%s%s(%s)%s" % (decorated, entry.name, entry.signature,
                          " -> %s" % entry.returns if entry.returns else "")
    line = "- `%s:%d` `%s` %s%s" % (entry.relpath, entry.lineno, sig,
                                    TAG, entry.tag)
    out = [line]
    if entry.doc:
        out.append("  - %s" % _cut(entry.doc, 110))
    return out


def render_module(module: Module) -> str:
    out = [BANNER.rstrip("\n"), "",
           "# `%s` — tier 2 %s%s" % (module.relpath, TAG, module.tag), ""]
    if module.doc:
        out += ["> %s" % _cut(module.doc, 160), ""]
    out += ["`%s` · %d lines · tier 1: [`../MAP.md`](../MAP.md)"
            % (module.dotted, module.lines), ""]
    if module.imports:
        out += ["**First-party imports.** `scripts/` may never import "
                "`editor/` — this line is where that is auditable.", "",
                "    " + " ".join(module.imports), ""]

    if module.constants:
        out += ["## Module constants", ""]
        for entry in module.constants:
            out.append("- `%s:%d` `%s` %s%s"
                       % (entry.relpath, entry.lineno, entry.name, TAG, entry.tag))
        out.append("")

    functions = module.functions
    if functions:
        out += ["## Functions", ""]
        for entry in sorted(functions, key=lambda e: e.lineno):
            out += _render_callable(entry)
        out.append("")

    classes = module.classes
    if classes:
        out += ["## Classes", ""]
        for entry in sorted(classes, key=lambda e: e.lineno):
            bases = "(%s)" % ", ".join(entry.bases) if entry.bases else ""
            decorated = "".join("@%s " % d for d in entry.decorators)
            out += ["### `%sclass %s%s` %s%s"
                    % (decorated, entry.name, bases, TAG, entry.tag), "",
                    "`%s:%d`–`%d`" % (entry.relpath, entry.lineno,
                                      entry.end_lineno), ""]
            if entry.doc:
                out += ["> %s" % _cut(entry.doc, 160), ""]
            methods = module.methods_of(entry.name)
            if methods:
                for method in sorted(methods, key=lambda e: e.lineno):
                    out += _render_callable(method)
            else:
                out.append("- (no methods)")
            out.append("")

    if not (module.constants or functions or classes):
        out += ["This module defines no class, function or public constant.", ""]
    return "\n".join(out).rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# Write / verify
# ---------------------------------------------------------------------------

def expected() -> dict[str, str]:
    """Every file this generator owns -> exactly what it should contain."""
    modules = load()
    out = {INDEX_REL: render_index(modules)}
    for module in modules:
        out[tier2_rel(module)] = render_module(module)
    return out


def on_disk_tier2() -> list[str]:
    directory = os.path.join(ROOT, TIER2_DIR.replace("/", os.sep))
    if not os.path.isdir(directory):
        return []
    return sorted("%s/%s" % (TIER2_DIR, name)
                  for name in os.listdir(directory) if name.endswith(".md"))


def write_all() -> tuple[int, int]:
    """Write every generated file; delete tier-2 files with no module.

    Deleting is half the job. A map file left behind by a deleted module is
    exactly the failure this generator exists to prevent, and it is the one a
    writer never notices.
    """
    want = expected()
    directory = os.path.join(ROOT, TIER2_DIR.replace("/", os.sep))
    os.makedirs(directory, exist_ok=True)
    for rel, body in want.items():
        path = os.path.join(ROOT, rel.replace("/", os.sep))
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(body)
    removed = 0
    for rel in on_disk_tier2():
        if rel not in want:
            os.remove(os.path.join(ROOT, rel.replace("/", os.sep)))
            removed += 1
    return len(want), removed


def drift() -> list[str]:
    """Human-readable reasons the files on disk are not what they should be."""
    want = expected()
    problems: list[str] = []
    for rel, body in want.items():
        path = os.path.join(ROOT, rel.replace("/", os.sep))
        if not os.path.isfile(path):
            problems.append("%s is missing" % rel)
            continue
        with open(path, encoding="utf-8", newline="") as handle:
            found = handle.read().replace("\r\n", "\n")
        if found != body:
            a, b = found.split("\n"), body.split("\n")
            where = next((i for i in range(max(len(a), len(b)))
                          if a[i:i + 1] != b[i:i + 1]), 0)
            problems.append("%s differs at line %d: on disk %r, should be %r"
                            % (rel, where + 1,
                               (a[where:where + 1] or ["<eof>"])[0][:70],
                               (b[where:where + 1] or ["<eof>"])[0][:70]))
    for rel in on_disk_tier2():
        if rel not in want:
            problems.append("%s maps a module that no longer exists" % rel)
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--write", action="store_true",
                        help="regenerate docs/MAP.md and docs/map/*.md")
    parser.add_argument("--tags", action="store_true",
                        help="print the tag index and exit")
    args = parser.parse_args(argv)

    if args.tags:
        for tag, site in sorted(tag_index().items()):
            print("%-52s %-8s %s" % (TAG + tag, site.kind, site.address))
        return 0
    if args.write:
        written, removed = write_all()
        print("wrote %d file(s) (%s + %d tier-2)"
              % (written, INDEX_REL, written - 1))
        if removed:
            print("removed %d orphaned tier-2 file(s)" % removed)
        return 0

    problems = drift()
    for problem in problems:
        print("  DRIFT " + problem)
    if problems:
        print("\n%d problem(s). Regenerate:\n    %s"
              % (len(problems), REGENERATE))
        return 1
    modules = load()
    print("map is current: %d modules, %d tags"
          % (len(modules), len(tag_index(modules))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
